### ISSUE TITLE
cogvlm2 使用多张a100 sft微调 报错  “all tensors to be on the same device”

### ISSUE THREAD

**Issue by GuoXu-booo** [modelscope/swift#1068]
@Jintao-Huang Hi!
**Describe the bug**
我使用的命令：
CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft \
    --model_type cogvlm2-19b-chat \
    --model_id_or_path /root/data/cogvlm2-llama3-chinese-chat-19B/ \
    --dataset /root/data/dataset/swift_train_file_v1.jsonl \
    --val_dataset /root/data/dataset/swift_val_file_v1.jsonl \
    --system '' \
    --eval_steps 30 \
    --logging_steps 5 \
    --output_dir output \
    --num_train_epochs 3 \
    --lora_target_modules ALL \
    --sft_type 'lora' 

报错：
![企业微信截图_1717507604581](https://github.com/modelscope/swift/assets/54988783/13eb5ffd-878d-4923-b9d2-20b30fbde4dc)
Traceback (most recent call last):
  File "/root/data/swift-2.0.5/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/root/data/swift-2.0.5/swift/utils/run_utils.py", line 27, in x_main
    result = llm_x(args, **kwargs)
  File "/root/data/swift-2.0.5/swift/llm/sft.py", line 286, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/root/data/swift-2.0.5/swift/trainers/trainers.py", line 50, in train
    res = super().train(*args, **kwargs)
  File "/root/miniconda3/envs/cogvlm2/lib/python3.10/site-packages/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/cogvlm2/lib/python3.10/site-packages/transformers/trainer.py", line 2216, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/miniconda3/envs/cogvlm2/lib/python3.10/site-packages/transformers/trainer.py", line 3238, in training_step
    loss = self.compute_loss(model, inputs)
 File "/root/data/swift-2.0.5/swift/trainers/trainers.py", line 188, in compute_loss
    outputs = model(**inputs)
  File "/root/miniconda3/envs/cogvlm2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/cogvlm2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/cogvlm2/lib/python3.10/site-packages/accelerate/utils/operations.py", line 822, in forward
    return model_forward(*args, **kwargs)
....
File "/root/miniconda3/envs/cogvlm2/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 569, in forward
    result = result + lora_B(lora_A(dropout(x))) * scaling
  File "/root/miniconda3/envs/cogvlm2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/cogvlm2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/cogvlm2/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
**RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:3! (when checking argument for argument mat2 in method wrapper_CUDA_mm)**
Train:   0%|

**Your hardware and system info**
部分包：
torch                                    2.3.0
torchvision                              0.18.0
tqdm                                     4.66.4
transformers                             4.41.0
transformers-stream-generator            0.0.5
triton                                   2.3.0
trl                                      0.8.6
typer                                    0.12.3
typing_extensions                        4.11.0
typing-inspect                           0.9.0
tyro                                     0.8.4
tzdata                                   2024.1
uptrace                                  1.24.0
urllib3                                  2.2.1
uvicorn                                  0.29.0
watchfiles                               0.20.0
websockets                               11.0.3
Werkzeug                                 3.0.3
wheel                                    0.43.0
wrapt                                    1.16.0
wsproto                                  1.2.0
xformers                                 0.0.26.post1
xxhash                                   3.4.1

 CUDA Version: 12.4

**Additional context**
我使用单卡、双卡和三卡都会报显存溢出的错误，再多的a100卡会报上面的错误。

非常期待您的回答！

**Comment by Jintao-Huang** [comment]
fixed

**Comment by GuoXu-booo** [comment]
> 固定

hi @Jintao-Huang  我刚clone了最新的代码 但微调cogvlm2依然有这个错误

**Comment by zhuliyi0** [comment]
单张A800使用 --lora_target_modules ALL  也是到OOM，DEFAULT无此问题。
