### ISSUE TITLE
微调seqgpt后，使用微调过后的ckpt作为resume_from_ckpt参数，报错

### ISSUE THREAD

**Issue by wickedsickk** [modelscope/swift#107]
Traceback (most recent call last):
  File "src/llm_sft.py", line 242, in <module>
    llm_sft(args)
  File "src/llm_sft.py", line 218, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/root/anaconda3/envs/swift/lib/python3.8/site-packages/transformers/trainer.py", line 1553, in train
    return inner_training_loop(
  File "/root/anaconda3/envs/swift/lib/python3.8/site-packages/transformers/trainer.py", line 1705, in _inner_training_loop
    self._load_optimizer_and_scheduler(resume_from_checkpoint)
  File "/root/anaconda3/envs/swift/lib/python3.8/site-packages/transformers/trainer.py", line 2496, in _load_optimizer_and_scheduler
    self.optimizer.load_state_dict(
  File "/root/anaconda3/envs/swift/lib/python3.8/site-packages/accelerate/optimizer.py", line 107, in load_state_dict
    self.optimizer.load_state_dict(state_dict)
  File "/root/anaconda3/envs/swift/lib/python3.8/site-packages/torch/optim/optimizer.py", line 390, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

**Comment by Jintao-Huang** [comment]
好的 我测试一下 稍等

**Comment by wickedsickk** [comment]
> 好的 我测试一下 稍等

请问有复现这个问题吗

**Comment by Jintao-Huang** [comment]
复现了

**Comment by wickedsickk** [comment]
> 复现了

好的 辛苦跟进下哈
