### ISSUE TITLE
internvl1.5  infer and finetune error

### ISSUE THREAD

**Issue by cyj95** [modelscope/swift#1100]
[INFO:swift] Please enter the conversation content first, followed by the path to the multimedia file.
<<< what is the imae
Input a media path or URL <<< /data/cuiyajie/swift-main/asset/wechat.png
Exception in thread Thread-2 (generate):
Traceback (most recent call last):
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/data/cuiyajie/swift-main/swift/llm/utils/model.py", line 3231, in _new_generate
    return generate(*args, **kwargs)
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/cuiyajie/.cache/huggingface/modules/transformers_modules/InternVL-Chat-V1-5/modeling_internvl_chat.py", line 339, in generate
    vit_embeds = self.extract_feature(pixel_values)
  File "/data/cuiyajie/swift-main/swift/llm/utils/model.py", line 3241, in _new_extract_feature
    return extract_feature(pixel_values).to(pixel_values.device).to(pixel_values.dtype)
  File "/home/cuiyajie/.cache/huggingface/modules/transformers_modules/InternVL-Chat-V1-5/modeling_internvl_chat.py", line 211, in extract_feature
    vit_embeds = self.vision_model(
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/cuiyajie/.cache/huggingface/modules/transformers_modules/InternVL-Chat-V1-5/modeling_intern_vit.py", line 408, in forward
    hidden_states = self.embeddings(pixel_values)
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/cuiyajie/.cache/huggingface/modules/transformers_modules/InternVL-Chat-V1-5/modeling_intern_vit.py", line 163, in forward
    patch_embeds = self.patch_embedding(pixel_values)  # shape = [*, channel, width, height]
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

what cuda version is needed?
where are the official settings that I can check ?

**Comment by hjh0119** [comment]
看起来像CUDA环境的问题, 找找相关issue？
