### ISSUE TITLE
如何部署微调后的模型？

### ISSUE THREAD

**Issue by David-19940718** [modelscope/swift#1112]
您好，我这边基于自定义数据对 `phi3-vision-128k-instruct` 进行微调，目前通过 `swift infer --ckpt_dir xxx` 的方式可以正常的执行推理。请问如何使用 python 代码进行推理？ 

1. 根据提供的 [MLLM部署文档](https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/MLLM%E9%83%A8%E7%BD%B2%E6%96%87%E6%A1%A3.md)，貌似只能通过 model_id 字段指定内部集成的模型，如何指定自定义模型的路径。
2. 此外，当我尝试运行该推理代码时：

```python
from swift.llm import get_model_list_client, XRequestConfig, inference_client

model_list = get_model_list_client()
model_type = model_list.data[0].id
print(f'model_type: {model_type}')

...
```
会抛出异常:

```bash
Traceback (most recent call last):
  File "swift/test_deploy.py", line 3, in <module>
    model_list = get_model_list_client()
  File "swift/swift/llm/utils/client_utils.py", line 22, in get_model_list_client
    resp_obj = requests.get(url).json()
  File "swift/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by David-19940718** [comment]
pip list 如下：
```
Package                       Version     Editable project location
----------------------------- ----------- --------------------------------------
absl-py                       2.1.0
accelerate                    0.28.0
addict                        2.4.0
aiofiles                      23.2.1
aiohttp                       3.9.3
aiosignal                     1.3.1
aliyun-python-sdk-core        2.15.0
aliyun-python-sdk-kms         2.16.2
altair                        5.2.0
annotated-types               0.6.0
anyio                         4.3.0
async-timeout                 4.0.3
attrs                         23.2.0
binpacking                    1.5.2
certifi                       2024.2.2
cffi                          1.16.0
charset-normalizer            3.3.2
click                         8.1.7
colorama                      0.4.6
coloredlogs                   15.0.1
contourpy                     1.2.0
cpm-kernels                   1.0.11
crcmod                        1.7
cryptography                  42.0.5
cycler                        0.12.1
dacite                        1.8.1
datasets                      2.18.0
dill                          0.3.8
docstring-parser              0.15
einops                        0.7.0
exceptiongroup                1.2.0
fastapi                       0.110.0
ffmpy                         0.3.2
filelock                      3.13.1
flash-attn                    2.5.9.post1
fonttools                     4.49.0
frozenlist                    1.4.1
fsspec                        2024.2.0
future                        1.0.0
gast                          0.5.4
gradio                        4.29.0
gradio_client                 0.16.1
grpcio                        1.62.1
h11                           0.14.0
httpcore                      1.0.4
httpx                         0.27.0
huggingface-hub               0.21.4
humanfriendly                 10.0
idna                          3.6
importlib_metadata            7.0.2
importlib_resources           6.3.0
jieba                         0.42.1
Jinja2                        3.1.3
jmespath                      0.10.0
joblib                        1.3.2
jsonschema                    4.21.1
jsonschema-specifications     2023.12.1
kiwisolver                    1.4.5
Markdown                      3.5.2
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.8.3
mdurl                         0.1.2
modelscope                    1.15.0
mpmath                        1.3.0
ms-swift                      2.2.0.dev0  workspace/mllm/swift
multidict                     6.0.5
multiprocess                  0.70.16
networkx                      3.2.1
nltk                          3.8.1
numpy                         1.26.4
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.19.3
nvidia-nvjitlink-cu12         12.4.99
nvidia-nvtx-cu12              12.1.105
optimum                       1.17.1
orjson                        3.9.15
oss2                          2.18.4
packaging                     24.0
pandas                        2.2.1
peft                          0.11.1
pillow                        10.2.0
pip                           23.3.1
platformdirs                  4.2.0
protobuf                      5.26.0
psutil                        5.9.8
pyarrow                       15.0.1
pyarrow-hotfix                0.6
pycparser                     2.21
pycryptodome                  3.20.0
pydantic                      2.6.4
pydantic_core                 2.16.3
pydub                         0.25.1
Pygments                      2.17.2
pyparsing                     3.1.2
python-dateutil               2.9.0.post0
python-multipart              0.0.9
pytz                          2024.1
PyYAML                        6.0.1
referencing                   0.33.0
regex                         2023.12.25
requests                      2.31.0
rich                          13.7.1
rouge                         1.0.1
rpds-py                       0.18.0
ruff                          0.3.2
safetensors                   0.4.2
scipy                         1.12.0
semantic-version              2.10.0
sentencepiece                 0.2.0
setuptools                    68.2.2
shellingham                   1.5.4
shtab                         1.7.1
simplejson                    3.19.2
six                           1.16.0
sniffio                       1.3.1
sortedcontainers              2.4.0
starlette                     0.36.3
sympy                         1.12
tensorboard                   2.16.2
tensorboard-data-server       0.7.2
tiktoken                      0.6.0
tokenizers                    0.15.2
tomli                         2.0.1
tomlkit                       0.12.0
toolz                         0.12.1
torch                         2.2.2
torchvision                   0.17.2
tqdm                          4.66.2
transformers                  4.38.2
transformers-stream-generator 0.0.5
triton                        2.2.0
trl                           0.9.4
typer                         0.12.3
typing_extensions             4.10.0
tyro                          0.7.3
tzdata                        2024.1
urllib3                       2.2.1
uvicorn                       0.28.0
websockets                    11.0.3
Werkzeug                      3.0.1
wheel                         0.41.2
xxhash                        3.4.1
yapf                          0.40.2
yarl                          1.9.4
zipp                          3.18.0
```

**Comment by David-19940718** [comment]
好像需要先运行服务端。不过运行时直接提示接口错误：
```
INFO:     Started server process [3394567]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8301 (Press CTRL+C to quit)
INFO:     127.0.0.1:51392 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51392 - "GET /favicon.ico HTTP/1.1" 404 Not Found
```

**Comment by Jintao-Huang** [comment]
get_model_list_client 额外传入 port

**Comment by David-19940718** [comment]
> get_model_list_client 额外传入 port

谢谢
