### ISSUE TITLE
local variable 'labels' referenced before assignment

### ISSUE THREAD

**Issue by cyj95** [modelscope/swift#1116]
自定义数据集微调internvl1-5，报错：

Traceback (most recent call last):
  File "/../swift-main/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/../swift-main/swift/utils/run_utils.py", line 27, in x_main
    result = llm_x(args, **kwargs)
  File "/../swift-main/swift/llm/sft.py", line 244, in llm_sft
    td0, tkwargs0 = template.encode(train_dataset[0])
  File "/../swift-main/swift/llm/utils/template.py", line 1001, in encode
    if labels is not None:
UnboundLocalError: local variable 'labels' referenced before assignment

**Comment by hjh0119** [comment]
@cyj95  麻烦说明下运行命令和数据集样例

**Comment by hjh0119** [comment]
我知道哪的bug了，稍等修复

**Comment by hjh0119** [comment]
fixed
