### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by huai-ying** [modelscope/swift#1153]
我在使用swift微调qwen1.5-14b-chat的时候如下：

```
2024-06-17 16:40:45,267 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 6a6e6831ffc7e596bd50384d6fb8900e and a total number of 980 components indexed
Traceback (most recent call last):
  File "/root/autodl-tmp/swift/swift/cli/sft.py", line 2, in <module>
    from swift.llm import sft_main
  File "/root/autodl-tmp/swift/swift/llm/__init__.py", line 5, in <module>
    from .utils import *
  File "/root/autodl-tmp/swift/swift/llm/utils/__init__.py", line 2, in <module>
    from .argument import (AppUIArguments, DeployArguments, DPOArguments, EvalArguments, ExportArguments, InferArguments,
  File "/root/autodl-tmp/swift/swift/llm/utils/argument.py", line 27, in <module>
    from .client_utils import get_model_list_client
  File "/root/autodl-tmp/swift/swift/llm/utils/client_utils.py", line 17, in <module>
    from .template import History
  File "/root/autodl-tmp/swift/swift/llm/utils/template.py", line 15, in <module>
    from swift.llm.agent.utils import calculate_loss_scale, get_tools_prompt
  File "/root/autodl-tmp/swift/swift/llm/agent/__init__.py", line 1, in <module>
    from .utils import calculate_loss_scale, get_tools_prompt, split_action_action_input
  File "/root/autodl-tmp/swift/swift/llm/agent/utils.py", line 71, in <module>
    response_loss_scale_map: Optional[dict[str, list]] = None,
TypeError: 'type' object is not subscriptable
```

下面是我的微调指令：

```
CUDA_VISIBLE_DEVICES=0 \
MASTER_PORT=29500 \
swift sft \
    --model_type qwen1half-14b-chat \
    --model_id_or_path /root/autodl-tmp/modelscope/hub/qwen/Qwen1___5-14B-Chat \
    --model_revision master \
    --sft_type lora \
    --tuner_backend swift \
    --template_type qwen \
    --dtype AUTO \
    --output_dir /root/autodl-tmp/out \
    --custom_train_dataset_path /root/autodl-tmp/datasyuan.jsonl \
    --train_dataset_sample -1 \
    --num_train_epochs 1 \
    --max_length 4096 \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules ALL \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 16 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --save_only_model true

```

**Comment by yihp** [comment]
重新拉取仓库试一下

**Comment by Jintao-Huang** [comment]
fixed
