### ISSUE TITLE
拉取最新commit之后internvl训练不支持多图

### ISSUE THREAD

**Issue by shaoyan1223** [modelscope/swift#1239]
请教一下，更新后的internvltemplate中增加了check_example的函数，用于判断当前传入的图片是否是单图，多图则会抛出异常，可以理解为当前internvl不支持多图了吗？但我看下面encode中又会出现多图的逻辑，如果把 assert len(images) 改为 <=10则会出现张量维度不匹配的问题，求解答，具体如下文：
```
class InternvlTemplate(Template):
    system = 'You are an AI assistant whose name is InternLM (书生·浦语).'
    num_image_token = 256

    def __init__(self):
        super().__init__(['<s>'], ['<|im_start|>user\n{{QUERY}}<|im_end|><|im_start|>assistant\n'], ['<|im_end|>'],
                         ['<|im_end|>'], self.system, ['<|im_start|>system\n{{SYSTEM}}<|im_end|>'])

    def check_example(self, example):
        images = example.get('images') or []
        assert len(images) <= 1

    def replace_tag(self, media_type, index, example) -> List[Context]:
        assert media_type == 'image'
        return [[-100]]

    def encode(self, example: Dict[str, Any]) -> Tuple[Dict[str, Any], Dict[str, Any]]:
        inputs, _ = super().encode(example)
        if len(inputs) == 0:
            return inputs, {}
        input_ids = inputs['input_ids']
        idx_list = _findall(input_ids, -100)
        labels = inputs.get('labels')
        images_path = example.get('images') or []
        if images_path:
            from .vision_utils import load_image

            pixel_values = []
            if isinstance(images_path, str):
                images_path = [images_path]
            for image_path in images_path:
                pixel_values.append(load_image(image_path))
            pixel_values = torch.cat(pixel_values, dim=0)
            image_bs = pixel_values.shape[0]
```

```
[rank7]: Traceback (most recent call last):
[rank7]:   File "/mnt/bn/lesqa-quality-data-yg/project/swift/swift/cli/sft.py", line 5, in <module>
[rank7]:     sft_main()
[rank7]:   File "/mnt/bn/lesqa-quality-data-yg/project/swift/swift/utils/run_utils.py", line 27, in x_main
[rank7]:     result = llm_x(args, **kwargs)
[rank7]:   File "/mnt/bn/lesqa-quality-data-yg/project/swift/swift/llm/sft.py", line 310, in llm_sft
[rank7]:     trainer.train(training_args.resume_from_checkpoint)
[rank7]:   File "/mnt/bn/lesqa-quality-data-yg/project/swift/swift/trainers/mixin.py", line 517, in train
[rank7]:     res = super().train(resume_from_checkpoint, *args, **kwargs)
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 1885, in train
[rank7]:     return inner_training_loop(
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 2216, in _inner_training_loop
[rank7]:     tr_loss_step = self.training_step(model, inputs)
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 3238, in training_step
[rank7]:     loss = self.compute_loss(model, inputs)
[rank7]:   File "/mnt/bn/lesqa-quality-data-yg/project/swift/swift/trainers/trainers.py", line 183, in compute_loss
[rank7]:     outputs = model(**inputs)
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank7]:     return self._call_impl(*args, **kwargs)
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank7]:     return forward_call(*args, **kwargs)
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
[rank7]:     ret_val = func(*args, **kwargs)
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1855, in forward
[rank7]:     loss = self.module(*inputs, **kwargs)
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank7]:     return self._call_impl(*args, **kwargs)
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank7]:     return forward_call(*args, **kwargs)
[rank7]:   File "/mnt/bn/lesqa-quality-data-yg/project/swift/swift/llm/utils/model.py", line 3325, in _new_forward
[rank7]:     return forward(*args, **kwargs)
[rank7]:   File "/home/tiger/.cache/huggingface/modules/transformers_modules/Mini-InternVL-Chat-2B-V1-5/modeling_internvl_chat.py", line 127, in forward
[rank7]:     vit_embeds = self.extract_feature(pixel_values)
[rank7]:   File "/mnt/bn/lesqa-quality-data-yg/project/swift/swift/llm/utils/model.py", line 3346, in _new_extract_feature
[rank7]:     return extract_feature(pixel_values).to(pixel_values.device).to(pixel_values.dtype)
[rank7]:   File "/home/tiger/.cache/huggingface/modules/transformers_modules/Mini-InternVL-Chat-2B-V1-5/modeling_internvl_chat.py", line 211, in extract_feature
[rank7]:     vit_embeds = self.vision_model(
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank7]:     return self._call_impl(*args, **kwargs)
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank7]:     return forward_call(*args, **kwargs)
[rank7]:   File "/home/tiger/.cache/huggingface/modules/transformers_modules/Mini-InternVL-Chat-2B-V1-5/modeling_intern_vit.py", line 415, in forward
[rank7]:     hidden_states = self.embeddings(pixel_values)
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank7]:     return self._call_impl(*args, **kwargs)
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank7]:     return forward_call(*args, **kwargs)
[rank7]:   File "/home/tiger/.cache/huggingface/modules/transformers_modules/Mini-InternVL-Chat-2B-V1-5/modeling_intern_vit.py", line 169, in forward
[rank7]:     patch_embeds = self.patch_embedding(pixel_values)  # shape = [*, channel, width, height]
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank7]:     return self._call_impl(*args, **kwargs)
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank7]:     return forward_call(*args, **kwargs)
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
[rank7]:     return self._conv_forward(input, self.weight, self.bias)
[rank7]:   File "/opt/conda/envs/swift/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
[rank7]:     return F.conv2d(input, weight, bias, self.stride,
[rank7]: RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```

**Comment by Jintao-Huang** [comment]
fixed
