### ISSUE TITLE
采用qlora，使用的是Qwen-7b-chat，本地数据集，出现这样的报错。我之前用lora的方式是OK的。

### ISSUE THREAD

**Issue by Jethu1** [modelscope/swift#127]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/train_file//opensource/swift-main/examples/pytorch/llm/llm_sft.py", line 2, in <module>
    import custom
  File "/train_file/xx/opensource/swift-main/examples/pytorch/llm/custom.py", line 8, in <module>
    from swift.llm import (ConversationsPreprocessor,QueryPreprocessor, LoRATM, Template,TemplateType,
  File "/train_file/xxx/opensource/swift-main/swift/llm/__init__.py", line 2, in <module>
    from .infer import llm_infer
  File "/train_file/xx/opensource/swift-main/swift/llm/infer.py", line 6, in <module>
    from modelscope import BitsAndBytesConfig, GenerationConfig
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/opt/conda/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 422, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/opt/conda/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 441, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import modelscope.utils.hf_util because of the following error (look up to see its traceback):
Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by Jintao-Huang** [comment]
看起来是您的机器不支持bitsandbytes. 你试试 qwen-7b-chat-int4. 使用的是auto_gptq量化.
