### ISSUE TITLE
InternVL2-26B微调模型报错

### ISSUE THREAD

**Issue by YasmineXXX** [modelscope/swift#1313]
感谢7.6的发布的针对internvl2的新版本！但是运行InternVL2-26B会出现如下报错：
ValueError: Unrecognized configuration class <class 'transformers_modules.InternVL2-26B.configuration_internvl_chat.InternVLChatConfig'> to build an AutoTokenizer.

亲测InternVL2-8B/2B没有问题，已经更新过transformers版本，但仍然报错，请问是什么原因呢？

**Comment by hjh0119** [comment]
看起来像模型的config.json有问题, 你可以试试将本地模型的config.json文件换成[hf版本](https://huggingface.co/OpenGVLab/InternVL2-26B/blob/main/config.json)的

**Comment by Tonikroosliruhao** [comment]
我也有类似的问题，sft之后跑inference的时候报错：
[INFO:swift] Loading the model using model_dir: /apdcephfs_cq11/share_1567347/share_info/ruhaoli/sft-internvl2-ckpt/internvl2-8b/v6-20240802-154109/checkpoint-1600
Traceback (most recent call last):
  File "/apdcephfs_cq10/share_1567347/share_info/ruhaoli/swift/swift/cli/infer.py", line 5, in <module>
    infer_main()
  File "/apdcephfs_cq10/share_1567347/share_info/ruhaoli/swift/swift/utils/run_utils.py", line 27, in x_main
    result = llm_x(args, **kwargs)
  File "/apdcephfs_cq10/share_1567347/share_info/ruhaoli/swift/swift/llm/infer.py", line 297, in llm_infer
    model, template = prepare_model_template(args, device_map=device_map)
  File "/apdcephfs_cq10/share_1567347/share_info/ruhaoli/swift/swift/llm/infer.py", line 184, in prepare_model_template
    model, tokenizer = get_model_tokenizer(
  File "/apdcephfs_cq10/share_1567347/share_info/ruhaoli/swift/swift/llm/utils/model.py", line 5904, in get_model_tokenizer
    model, tokenizer = get_function(model_dir, torch_dtype, model_kwargs, load_model, **kwargs)
  File "/apdcephfs_cq10/share_1567347/share_info/ruhaoli/swift/swift/llm/utils/model.py", line 3906, in get_model_tokenizer_internvl
    model, tokenizer = get_model_tokenizer_from_repo(
  File "/apdcephfs_cq10/share_1567347/share_info/ruhaoli/swift/swift/llm/utils/model.py", line 935, in get_model_tokenizer_from_repo
    tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
  File "/data/miniconda3/envs/swift/lib/python3.10/site-packages/modelscope/utils/hf_util.py", line 113, in from_pretrained
    module_obj = module_class.from_pretrained(model_dir, *model_args,
  File "/data/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 918, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.checkpoint-1600.configuration_internvl_chat.InternVLChatConfig'> to build an AutoTokenizer.
Model type should be one of AlbertConfig, AlignConfig, BarkConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, Blip2Config, BloomConfig, BridgeTowerConfig, BrosConfig, CamembertConfig, CanineConfig, ChineseCLIPConfig, ClapConfig, CLIPConfig, CLIPSegConfig, ClvpConfig, LlamaConfig, CodeGenConfig, CohereConfig, ConvBertConfig, CpmAntConfig, CTRLConfig, Data2VecAudioConfig, Data2VecTextConfig, DbrxConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, DPRConfig, ElectraConfig, ErnieConfig, ErnieMConfig, EsmConfig, FalconConfig, FastSpeech2ConformerConfig, FlaubertConfig, FNetConfig, FSMTConfig, FunnelConfig, GemmaConfig, Gemma2Config, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GPTSanJapaneseConfig, GroundingDinoConfig, GroupViTConfig, HubertConfig, IBertConfig, IdeficsConfig, Idefics2Config, InstructBlipConfig, InstructBlipVideoConfig, JambaConfig, JetMoeConfig, JukeboxConfig, Kosmos2Config, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LiltConfig, LlamaConfig, LlavaConfig, LlavaNextVideoConfig, LlavaNextConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MambaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MgpstrConfig, MistralConfig, MixtralConfig, MobileBertConfig, MPNetConfig, MptConfig, MraConfig, MT5Config, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, NezhaConfig, NllbMoeConfig, NystromformerConfig, OlmoConfig, OneFormerConfig, OpenAIGPTConfig, OPTConfig, Owlv2Config, OwlViTConfig, PaliGemmaConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, PersimmonConfig, PhiConfig, Phi3Config, Pix2StructConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, Qwen2MoeConfig, RagConfig, RealmConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RetriBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, SeamlessM4TConfig, SeamlessM4Tv2Config, SiglipConfig, Speech2TextConfig, Speech2Text2Config, SpeechT5Config, SplinterConfig, SqueezeBertConfig, StableLmConfig, Starcoder2Config, SwitchTransformersConfig, T5Config, TapasConfig, TransfoXLConfig, TvpConfig, UdopConfig, UMT5Config, VideoLlavaConfig, ViltConfig, VipLlavaConfig, VisualBertConfig, VitsConfig, Wav2Vec2Config, Wav2Vec2BertConfig, Wav2Vec2ConformerConfig, WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YosoConfig.

**Comment by Ranking666** [comment]
请问有解决吗？我微调internvl2.5-1b也遇到这个问题了

**Comment by hjh0119** [comment]
栈信息和transformers版本？
