### ISSUE TITLE
Florence2 Python example doesn't work

### ISSUE THREAD

**Issue by SinanAkkoyun** [modelscope/swift#1441]
**Describe the bug**
Running the exact example inference code:

```py
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

from swift.llm import (
    get_model_tokenizer, get_template, inference,
    get_default_template_type, inference_stream
)
from swift.utils import seed_everything

model_type = "florence-2-large-ft"
template_type = get_default_template_type(model_type)
print(f'template_type: {template_type}')
model, tokenizer = get_model_tokenizer(model_type, model_kwargs={'device_map': "cuda:0"})

model.generation_config.max_new_tokens = 1024
template = get_template(template_type, tokenizer)
seed_everything(42)

images = ['http://modelscope-open.oss-cn-hangzhou.aliyuncs.com/images/animal.png']
query = 'Describe the image'
response, history = inference(model, template, query, images=images)
print(f'query: {query}')
print(f'response: {response}')
'''
query: Describe the image
response: {'Describe the image': 'Four sheep standing in a field with mountains in the background.'}
'''
```

returns:

```
template_type: florence
[INFO:swift] Downloading the model from ModelScope Hub, model_id: AI-ModelScope/Florence-2-large-ft
[INFO:swift] Loading the model using model_dir: /home/ai/.cache/modelscope/hub/AI-ModelScope/Florence-2-large-ft
[INFO:swift] Setting torch_dtype: torch.float16
[INFO:swift] model_kwargs: {'device_map': 'cuda:0'}
[INFO:swift] model.max_model_len: None
[INFO:swift] Global seed set to 42
Traceback (most recent call last):
  File "/home/ai/ml/llm/training/swift/inference_florence2.py", line 21, in <module>
    response, history = inference(model, template, query, images=images)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/.mconda3/envs/swift/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/.mconda3/envs/swift/lib/python3.11/site-packages/swift/llm/utils/utils.py", line 763, in inference
    inputs, tokenizer_kwargs, token_len, example = _prepare_inputs(
                                                   ^^^^^^^^^^^^^^^^
  File "/home/ai/.mconda3/envs/swift/lib/python3.11/site-packages/swift/llm/utils/utils.py", line 580, in _prepare_inputs
    inputs, tokenizer_kwargs = template.encode(example)
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/.mconda3/envs/swift/lib/python3.11/site-packages/swift/llm/utils/template.py", line 1601, in encode
    if inputs['labels'] is not None:
       ~~~~~~^^^^^^^^^^
  File "/home/ai/.mconda3/envs/swift/lib/python3.11/site-packages/transformers/feature_extraction_utils.py", line 86, in __getitem__
    return self.data[item]
           ~~~~~~~~~^^^^^^
KeyError: 'labels'

```

**Your hardware and system info**
CUDA 12.2, RTX 4090, everything else works fine

**Additional context**

**Comment by SinanAkkoyun** [comment]
Sorry, my bad, I was running in the wrong (older) docker container

**Comment by SinanAkkoyun** [comment]
(Repurposing this issue for another florence related one)

**Comment by z0o0ey** [comment]
Please try again using the latest versions of Swift and VLLM. If the problem persists or you have any new suggestions or comments, please feel free to create a new question.
