### ISSUE TITLE
Lora Internlm-Xcomposer2-4KHD的过程中发生OOM

### ISSUE THREAD

**Issue by bonre** [modelscope/swift#1494]
下面是我的训练脚本：
```
NODE_RANK=0 \
MASTER_ADDR=localhost \
MASTER_PORT=7777 \
NPROC_PER_NODE=8 \
swift sft \
    --model_type internlm-xcomposer2-7b-chat \
    --model_id_or_path /data/rotate_712 \
    --output_dir /data/adapter/0725_new \
    --gradient_checkpointing true \
    --num_train_epochs 1 \
    --sft_type lora \
    --use_flash_attn true \
    --batch_size 1 \
    --evaluation_strategy 'epoch' \
    --custom_train_dataset_path /data/train_data_0725/0725.json \
    --train_dataset_sample -1 \
    --custom_val_dataset_path /data/test/val_data/data.json \
    --val_dataset_sample -1 \
    --deepspeed default-zero2 \
```
共4910steps，每次会在大约600steps左右报错OOM，
设备为 8*A100 40G
尝试使用--deepspeed default-zero3和--deepspeed zero3--offload均会报错，
请问我还有什么地方可以优化来减少显存占用呢？
非常感谢如果您能帮我解答！
BTW，使用官方的finetune_lora脚本是可以lora的，但耗时很长，好像是包不兼容导致一些微调加速的方法没有应用成功，脚本如下：
```
GPUS_PER_NODE=6
NNODES=1
NODE_RANK=0
MASTER_ADDR=localhost
MASTER_PORT=6001

DISTRIBUTED_ARGS="
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --node_rank $NODE_RANK \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT
"

torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --img_size 490 \
    --hd_num 16 \
    --given_num True \
    --bf16 True \
    --fix_vit True \
    --fix_sampler True \
    --use_lora True \
    --output_dir /data/adapter/le_0725 \
    --num_train_epochs 1 \
    --batch_size 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "epoch" \
    --save_total_limit 1 \
    --learning_rate 3e-5 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --max_length 4096 \
    --deepspeed ds_config_zero2.json \
    --gradient_checkpointing True
```

**Comment by bonre** [comment]
--deepspeed default-zero3和--deepspeed zero3--offload报错日志：
```
Traceback (most recent call last):
  File "/home/swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/home/swift/swift/utils/run_utils.py", line 27, in x_main
    result = llm_x(args, **kwargs)
  File "/home/swift/swift/llm/sft.py", line 258, in llm_sft
    td0, tkwargs0 = template.encode(train_dataset[0])
  File "/home/swift/llm/utils/template.py", line 1300, in encode
    res_inputs_embeds.append(tok_embeddings(res_input_ids))
  File "/home/anaconda3/envs/ixc2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anaconda3/envs/ixc2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/anaconda3/envs/ixc2/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/home/anaconda3/envs/ixc2/lib/python3.9/site-packages/torch/nn/functional.py", line 2215, in embedding
    assert padding_idx < weight.size(0), "Padding_idx must be within num_embeddings"
AssertionError: Padding_idx must be within num_embeddings
```

**Comment by Jintao-Huang** [comment]
哈咯 最后是解决了嘛

**Comment by bonre** [comment]
嗯，设置max_length的长度就行，我这边的数据有些instruction比较长。
然而现在有问题的地方在于，swift调出来的模型事实上效果并没有internlm-xcomposer开源的微调脚本好，我对比了下应该是有些地方没有对齐，像是lora_target_modules之类的。
当然，很感谢你们的工作，swift在微调internvl的时候效果还是很好的，并且internlm-xcomposer微调时可以使用zero2，虽然repo中的脚本也用上了，但貌似是没有生效，也许是我的环境问题导致的。 @Jintao-Huang

**Comment by Jintao-Huang** [comment]
好的，感谢反馈
可以描述一下效果不好的具体表现嘛，是无法记住知识、回答重复、loss没有降低还是其他内容呢？
这可以帮助我们改进框架😊

**Comment by bonre** [comment]
@Jintao-Huang 对于我参与的项目而言，使用swift对比官方脚本，差异如下：
1.存在回答重复，且对于某些VQA问题会一直输出，产生幻觉。
2.记住的知识内容准确度不高。
我这边主要的微调目标是做ChartVQA，图表的样式比较不标准
上述差异的成因，就我个人理解上，可能是在这些参数上：
```
--img_size 490 \
    --hd_num 16 \
    --given_num True \
    --bf16 True \
    --fix_vit True \
    --fix_sampler True \
    --max_length 4096 \
```
swift按我的理解不确定有没有针对internlm-xcomposer做专门的对齐，也可能是我的使用不当。
总之，体验下来确实某些方面相较有优势，感谢你们的工作！
