### ISSUE TITLE
微调llama3_1系列模型出现报错

### ISSUE THREAD

**Issue by badmic** [modelscope/swift#1520]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
微调llama3_1模型出现报错：
Traceback (most recent call last):
  File "/data/project/ys/swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/data/project/ys/swift/swift/utils/run_utils.py", line 21, in x_main
    args, remaining_argv = parse_args(args_class, argv)
  File "/data/project/ys/swift/swift/utils/utils.py", line 131, in parse_args
    args, remaining_args = parser.parse_args_into_dataclasses(argv, return_remaining_strings=True)
  File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/transformers/hf_argparser.py", line 339, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 189, in __init__
  File "/data/project/ys/swift/swift/llm/utils/argument.py", line 857, in __post_init__
    self.set_model_type()
  File "/data/project/ys/swift/swift/llm/utils/argument.py", line 450, in set_model_type
    require_version(require)
  File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/transformers/utils/versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/transformers/utils/versions.py", line 44, in _compare_versions
    raise ImportError(
ImportError: transformers>=4.43 is required for a normal functioning of this module, but found transformers==4.42.4.

要求环境中的transformers必须大于等于4.43才行

但是将transformers升为4.43之后，出现环境中的包版本不匹配的错误：
optimum==1.21.2要求环境中的transformers必须小于4.43，并且optimum删掉也不行，运行不了微调。且optimum目前的最高版本为1.21.2。请问这个版本问题可以解决吗

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
不用管 optimum，直接跑就好了

**Comment by badmic** [comment]
但是直接跑的话会报错，把optimum卸载之后：
swift_cu) root@m1:/data/project/swift# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 NNODES=2 NODE_RANK=0 MASTER_ADDR=10.254.31.16 NPROC_PER_NODE=8 swift sft     --model_type llama3_1-405b-instruct     --model_id_or_path /data/models/Meta-Llama-3.1-405B-Instruct     --sft_type lora     --lora_target_modules q_proj k_proj v_proj     --use_flash_attn "True"     --lora_rank "128"  --dataset alpaca-zh     --output_dir output_2     --deepspeed default-zero3 
Traceback (most recent call last):
  File "/root/miniconda3/envs/swift_cu/bin/swift", line 33, in <module>
    sys.exit(load_entry_point('ms-swift', 'console_scripts', 'swift')())
  File "/root/miniconda3/envs/swift_cu/bin/swift", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/root/miniconda3/envs/swift_cu/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/root/miniconda3/envs/swift_cu/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/project/ys/swift/swift/__init__.py", line 4, in <module>
    from .utils.import_utils import _LazyModule
  File "/data/project/ys/swift/swift/utils/__init__.py", line 3, in <module>
    from .hub import create_ms_repo, push_to_ms_hub
  File "/data/project/ys/swift/swift/utils/hub.py", line 13, in <module>
    from .utils import subprocess_run
  File "/data/project/ys/swift/swift/utils/utils.py", line 15, in <module>
    from transformers.trainer import TrainingArguments
  File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/transformers/trainer.py", line 221, in <module>
    from accelerate.utils import (
ImportError: cannot import name 'is_mlu_available' from 'accelerate.utils' (/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/accelerate/utils/__init__.py)

**Comment by Jintao-Huang** [comment]
pip install accelerate -U

**Comment by YilaiLiu** [comment]
> pip install accelerate -U

您好，我再更新完accelerate以后还是会出现rope scaling的报错，我的transformers版本已经更新到了4.43.4
![image](https://github.com/user-attachments/assets/4b6e0ad0-194f-469d-817d-e16a44223ef9)

![image](https://github.com/user-attachments/assets/ac2d257c-5ffb-41ab-8bf5-f1f9d8e9d270)

**Comment by ArlanCooper** [comment]
这个解决了吗？怎么关掉了呢？

**Comment by YilaiLiu** [comment]
您好，就是更改一下accelerate，peft，transformers还有一些相关库的版本，我的具体的版本我后面用另一个电脑的时候可以发给你做参考
________________________________
发件人: cooper ***@***.***>
发送时间: 2024年8月19日 14:36
收件人: modelscope/ms-swift ***@***.***>
抄送: Yilai Liu ***@***.***>; Comment ***@***.***>
主题: Re: [modelscope/ms-swift] 微调llama3_1系列模型出现报错 (Issue #1520)


这个解决了吗？怎么关掉了呢？

―

**Comment by ArlanCooper** [comment]
好滴，谢谢，我也解决了
