### ISSUE TITLE
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

### ISSUE THREAD

**Issue by MindLostGuy** [modelscope/swift#1553]
当我尝试finetune deepseek vl时，遇到了runtime error

> Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/opt/conda/lib/python3.10/site-packages/swift/utils/run_utils.py", line 27, in x_main
    result = llm_x(args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/swift/llm/sft.py", line 317, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/opt/conda/lib/python3.10/site-packages/swift/trainers/mixin.py", line 518, in train
    res = super().train(resume_from_checkpoint, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1836, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/opt/conda/lib/python3.10/site-packages/accelerate/data_loader.py", line 384, in __iter__
    current_batch = next(dataloader_iter)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.10/site-packages/swift/llm/utils/utils.py", line 262, in __getitem__
    res = self._try_fetch(idx)
  File "/opt/conda/lib/python3.10/site-packages/swift/llm/utils/utils.py", line 273, in _try_fetch
    res = self.template.encode(data)
  File "/opt/conda/lib/python3.10/site-packages/swift/llm/utils/template.py", line 1984, in encode
    batched_output = batched_output.to(device=model.device, dtype=model.dtype)
  File "...../cache/modelscope/_github/DeepSeek-VL/deepseek_vl/models/processing_vlm.py", line 64, in to
    self.input_ids = self.input_ids.to(device)
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 284, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

使用的脚本为：

> pip install 'ms-swift[llm]' -U -i https://mirrors.bfsu.edu.cn/pypi/web/simple -q; \
  pip install transformers -i https://mirrors.bfsu.edu.cn/pypi/web/simple -q; \
  pip install Pillow -i https://mirrors.bfsu.edu.cn/pypi/web/simple -q; \
  pip install modelscope -i https://mirrors.bfsu.edu.cn/pypi/web/simple -q; \
  pip install importlib_metadata -i https://mirrors.bfsu.edu.cn/pypi/web/simple -q; \
  pip install attrdict oss2 addict -i https://mirrors.bfsu.edu.cn/pypi/web/simple -q; \
  pip install datasets==2.18.0 -i https://mirrors.bfsu.edu.cn/pypi/web/simple -q; \
  pip install -U timm -i https://mirrors.bfsu.edu.cn/pypi/web/simple -q; \
  pip install flash-attn --no-build-isolation -q; \
  export NCCL_SOCKET_IFNAME=enp24s0,enp25s0; \
  export MKL_THREADING_LAYER=GNU; \
  NNODES=8 NPROC_PER_NODE=4 CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft \
    --model_type deepseek-vl-1_3b-chat \
    --sft_type full \
    --dtype bf16 \
    --dataset ...../train.json \
    --val_dataset ......./val.json#300 \
    --save_only_model False \
    --dataset_test_ratio 0.0 \
    --max_length 4096 \
    --seed 42 \
    --dataset_seed 52 \
    --check_dataset_strategy warning \
    --use_flash_attn true \
    --num_train_epochs 5 \
    --dataloader_num_workers 4 \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 1 \
    --logging_steps 5 \
    --save_strategy epoch \
    --save_total_limit 5 \
    --eval_steps 1000 \
    --lr_scheduler_type cosine\
    --warmup_ratio 0.03 \
    --lazy_tokenize True \
    --gradient_checkpointing True \
    --deepspeed default-zero2;"

**Comment by Jintao-Huang** [comment]
这个模型 --dataloader_num_workers 0

**Comment by MindLostGuy** [comment]
Thanks！It works!
