### ISSUE TITLE
使用自定义评测集来评测微调后的模型，出现eval_backend错误。

### ISSUE THREAD

**Issue by dpl-naoc** [modelscope/swift#1568]
Traceback (most recent call last):
  File "/mnt/nas/home/dupengliang/swift/swift/cli/eval.py", line 5, in <module>
    eval_main()
  File "/mnt/nas/home/dupengliang/swift/swift/utils/run_utils.py", line 27, in x_main
    result = llm_x(args, **kwargs)
  File "/mnt/nas/home/dupengliang/swift/swift/llm/eval.py", line 323, in llm_eval
    return eval_llmuses(args)
  File "/mnt/nas/home/dupengliang/swift/swift/llm/eval.py", line 291, in eval_llmuses
    run_task(task_cfg=task_configs)
  File "/home/dupengliang/anaconda3/envs/swift/lib/python3.10/site-packages/llmuses/run.py", line 173, in run_task
    eval_results.append(run_task(one_task_cfg))
  File "/home/dupengliang/anaconda3/envs/swift/lib/python3.10/site-packages/llmuses/run.py", line 195, in run_task
    assert eval_config, f'Please provide the eval task config for evaluation backend {eval_backend}'
AssertionError: Please provide the eval task config for evaluation backend None

https://swift.readthedocs.io/zh-cn/latest/LLM/LLM%E8%AF%84%E6%B5%8B%E6%96%87%E6%A1%A3.html 使用的是这里面的方法，General-QA

**Comment by wangxingjun778** [comment]
please update the eval-scope dependency: pip install llmuses>=0.4.3 and try again.

**Comment by dpl-naoc** [comment]
> please update the eval-scope dependency: pip install llmuses>=0.4.3 and try again.

谢谢，解决了
