### ISSUE TITLE
使用deepspeed出现报错

### ISSUE THREAD

**Issue by badmic** [modelscope/swift#1574]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

脚本中带有    --deepspeed zero3-offload
这个参数，zero3和zero2同样也会出现报错

出现报错：
[rank0]:     self.ref_model = create_reference_model(model)
[rank0]:   File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/trl/models/modeling_base.py", line 624, in create_reference_model
[rank0]:     raise ValueError(
[rank0]: ValueError: DeepSpeed ZeRO-3 is enabled and is not compatible with `create_reference_model()`. Please instantiate your reference model directly with `AutoCausalLM.from_pretrained()`.
[rank7]: Traceback (most recent call last):
[rank7]:   File "/data/project/ys/swift/swift/cli/rlhf.py", line 5, in <module>
[rank7]:     rlhf_main()
[rank7]:   File "/data/project/ys/swift/swift/utils/run_utils.py", line 27, in x_main
[rank7]:     result = llm_x(args, **kwargs)
[rank7]:   File "/data/project/ys/swift/swift/llm/rlhf.py", line 207, in llm_rlhf
[rank7]:     trainer = trainer_cls(
[rank7]:   File "/data/project/ys/swift/swift/trainers/dpo_trainer.py", line 26, in __init__
[rank7]:     super().__init__(*args, **kwargs)
[rank7]:   File "/data/project/ys/swift/swift/trainers/mixin.py", line 242, in __init__
[rank7]:     super().__init__(
[rank7]:   File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
[rank7]:     return f(*args, **kwargs)
[rank7]:   File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/trl/trainer/dpo_trainer.py", line 383, in __init__
[rank7]:     self.ref_model = create_reference_model(model)
[rank7]:   File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/trl/models/modeling_base.py", line 624, in create_reference_model
[rank7]:     raise ValueError(
[rank7]: ValueError: DeepSpeed ZeRO-3 is enabled and is not compatible with `create_reference_model()`. Please instantiate your reference model directly with `AutoCausalLM.from_pretrained()`.

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by tastelikefeet** [comment]
DPO？
DPO和deepspeed目前不兼容的
