### ISSUE TITLE
当使用量化过的模型进行推理时报错

### ISSUE THREAD

**Issue by nicolasNi** [modelscope/swift#166]
使用如下命令进行推理时报错：
`CUDA_VISIBLE_DEVICES=0 swift infer --model_cache_dir /media/nickkf/plus/2023/models/llm/Tongyi-Finance-14B-Chat-Int4`
如果把模型换成Qwen-7B-Chat则可以正常推理。

报错信息：
`[OUTPUT]Traceback (most recent call last):
  File "/mnt/d3/virtualenv/Qwen/lib/python3.8/site-packages/swift/cli/infer.py", line 4, in <module>
    infer_main()
  File "/mnt/d3/virtualenv/Qwen/lib/python3.8/site-packages/swift/llm/utils/utils.py", line 194, in x_main
    return llm_x(args, **kwargs)
  File "/mnt/d3/virtualenv/Qwen/lib/python3.8/site-packages/swift/llm/infer.py", line 161, in llm_infer
    _, history = inference(
  File "/mnt/d3/virtualenv/Qwen/lib/python3.8/site-packages/swift/llm/utils/utils.py", line 399, in inference
    generate_ids = model.generate(
  File "/home/nickkf/.cache/huggingface/modules/transformers_modules/Tongyi-Finance-14B-Chat-Int4/modeling_qwen.py", line 1330, in generate
    return super().generate(
  File "/mnt/d3/virtualenv/Qwen/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/d3/virtualenv/Qwen/lib/python3.8/site-packages/transformers/generation/utils.py", line 1719, in generate
    return self.sample(
  File "/mnt/d3/virtualenv/Qwen/lib/python3.8/site-packages/transformers/generation/utils.py", line 2801, in sample
    outputs = self(
  File "/mnt/d3/virtualenv/Qwen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/d3/virtualenv/Qwen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nickkf/.cache/huggingface/modules/transformers_modules/Tongyi-Finance-14B-Chat-Int4/modeling_qwen.py", line 1120, in forward
    transformer_outputs = self.transformer(
  File "/mnt/d3/virtualenv/Qwen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/d3/virtualenv/Qwen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nickkf/.cache/huggingface/modules/transformers_modules/Tongyi-Finance-14B-Chat-Int4/modeling_qwen.py", line 950, in forward
    outputs = block(
  File "/mnt/d3/virtualenv/Qwen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/d3/virtualenv/Qwen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nickkf/.cache/huggingface/modules/transformers_modules/Tongyi-Finance-14B-Chat-Int4/modeling_qwen.py", line 653, in forward
    attn_outputs = self.attn(
  File "/mnt/d3/virtualenv/Qwen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/d3/virtualenv/Qwen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nickkf/.cache/huggingface/modules/transformers_modules/Tongyi-Finance-14B-Chat-Int4/modeling_qwen.py", line 573, in forward
    attn_output = F.scaled_dot_product_attention(
RuntimeError: Expected attn_mask dtype to be bool or to match query dtype, but got attn_mask.dtype: c10::BFloat16 and  query.dtype: c10::Half instead.
`

**Comment by Jintao-Huang** [comment]
CUDA_VISIBLE_DEVICES=0 swift infer --ckpt_dir /media/nickkf/plus/2023/models/llm/Tongyi-Finance-14B-Chat-Int4
