### ISSUE TITLE
请问加载本地模型和数据集报以下错误该如何解决，谢谢！

### ISSUE THREAD

**Issue by sjsj102323** [modelscope/swift#189]
运行命令行位置：
`swift/examples/pytorch/llm`

命令行
`#!/bin/bash
#SBATCH -o job2.out
#SBATCH --partition=GPU_s
#SBATCH --qos=normal
#SBATCH -J chatglm3
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --gres=gpu:1

PYTHONPATH=../../.. \
CUDA_VISIBLE_DEVICES=0 \
python llm_sft.py \
    --model_id_or_path ZhipuAI/chatglm3-6b \
    --model_cache_dir /public/home/zyz/.cache/modelscope/hub/ZhipuAI/chatglm3-6b
    --model_revision master \
    --sft_type lora \
    --tuner_backend swift \
    --template_type chatglm3 \
    --dtype AUTO \
    --output_dir output \
    --custom_train_dataset_path dataset.jsonl \
    --custom_val_dataset_path dataset.jsonl \
    --num_train_epochs 1 \
    --max_length 2048 \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules DEFAULT \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 16 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --push_to_hub false \
    --hub_model_id chatglm3-6b-lora \
    --hub_private_repo false \
    --hub_token 'your-sdk-token' \
`
报错界面：
```
`Traceback (most recent call last):
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x2b497d582680>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/urllib3/connectionpool.py", line 874, in urlopen
    return self.urlopen(
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/urllib3/connectionpool.py", line 874, in urlopen
    return self.urlopen(
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/datasets/AI-ModelScope/blossom-math-v2/oss/tree/?MaxLimit=-1&Revision=master&Recursive=True&FilterDir=True (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x2b497d582680>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/zyz/uniem/swift/examples/pytorch/llm/llm_sft.py", line 7, in <module>
    output = sft_main()
  File "/public/home/zyz/uniem/swift/swift/llm/utils/utils.py", line 199, in x_main
    return llm_x(args, **kwargs)
  File "/public/home/zyz/uniem/swift/swift/llm/sft.py", line 125, in llm_sft
    train_dataset, val_dataset = get_dataset(
  File "/public/home/zyz/uniem/swift/swift/llm/utils/dataset.py", line 764, in get_dataset
    dataset = get_function(
  File "/public/home/zyz/uniem/swift/swift/llm/utils/dataset.py", line 207, in get_dataset_from_repo
    dataset = load_ms_dataset(dataset_id, subset_split_list)
  File "/public/home/zyz/uniem/swift/swift/llm/utils/dataset.py", line 155, in load_ms_dataset
    dataset = MsDataset.load(
  File "/public/home/zyz/uniem/swift/swift/llm/utils/utils.py", line 82, in _msdataset_ddp_load
    dataset = _old_msdataset_load(*args, **kwargs)
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/modelscope/msdatasets/ms_dataset.py", line 284, in load
    dataset_inst = remote_dataloader_manager.load_dataset(
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/modelscope/msdatasets/data_loader/data_loader_manager.py", line 132, in load_dataset
    oss_downloader.process()
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/modelscope/msdatasets/data_loader/data_loader.py", line 82, in process
    self._build()
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/modelscope/msdatasets/data_loader/data_loader.py", line 109, in _build
    meta_manager.parse_dataset_structure()
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/modelscope/msdatasets/meta/data_meta_manager.py", line 132, in parse_dataset_structure
    meta_map, file_map, args_map, type_map = get_dataset_files(
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/modelscope/msdatasets/utils/dataset_utils.py", line 229, in get_dataset_files
    objects = list_dataset_objects(
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/modelscope/msdatasets/utils/dataset_utils.py", line 99, in list_dataset_objects
    objects = hub_api.list_oss_dataset_objects(
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/modelscope/hub/api.py", line 827, in list_oss_dataset_objects
    resp = self.session.get(url=url, cookies=cookies, timeout=1800)
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/public/home/zyz/.conda/envs/uniem/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/datasets/AI-ModelScope/blossom-math-v2/oss/tree/?MaxLimit=-1&Revision=master&Recursive=True&FilterDir=True (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x2b497d582680>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)"))
/public/slurm/spool/slurm/d/job1597441/slurm_script: line 20: --model_revision: command not found`
```

**Comment by sjsj102323** [comment]
> 你需要在`PYTHONPATH=../../..`后每一行的后面加上 '' 😊
感谢解答！
1.请问具体是什么形式呢，尝试了`--model_id_or_path 'ZhipuAI/chatglm3-6b'`和`--model_id_or_path=ZhipuAI/chatglm3-6b`都不行。
2.如果不用`--model_cache_dir /public/home/zyz/.cache/modelscope/hub/ZhipuAI/chatglm3-6b` 是不会产生`/public/slurm/spool/slurm/d/job1597441/slurm_script: line 20: --model_revision: command not found``的错误，只有`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/datasets/AI-ModelScope/blossom-math-v2/oss/tree/?MaxLimit=-1&Revision=master&Recursive=True&FilterDir=True (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x2b497d582680>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)"))`这个报错，请问这个报错是什么原因导致的呢？

**Comment by sjsj102323** [comment]
感谢解答！
