### ISSUE TITLE
在运行sh文件微调chatglm3-6b时，出现ValueError: Attempting to unscale FP16 gradients.

### ISSUE THREAD

**Issue by luke-kang** [modelscope/swift#225]
[INFO:swift] Model file tokenization_chatglm.py is different from the latest version `v1.0.2`,This is because you are using an older version or the file is updated manually.
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[INFO:swift] The SftArguments will be saved in: /root/autodl-tmp/swift/examples/pytorch/llm/output/chatglm3-6b/v5-20231216-185304/sft_args.json
[INFO:swift] The Seq2SeqTrainingArguments will be saved in: /root/autodl-tmp/swift/examples/pytorch/llm/output/chatglm3-6b/v5-20231216-185304/training_args.json
[INFO:swift] The logging file will be saved in: /root/autodl-tmp/swift/examples/pytorch/llm/output/chatglm3-6b/v5-20231216-185304/logging.jsonl
  0%|                                                                                                                                              | 0/618 [00:00<?, ?it/s]Traceback (most recent call last):
  File "llm_sft.py", line 7, in <module>
    output = sft_main()
  File "/root/autodl-tmp/swift/swift/utils/run_utils.py", line 27, in x_main
    return llm_x(args, **kwargs)
  File "/root/autodl-tmp/swift/swift/llm/sft.py", line 311, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1896, in _inner_training_loop
    self.accelerator.clip_grad_norm_(
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/accelerator.py", line 2040, in clip_grad_norm_
    self.unscale_gradients()
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/accelerator.py", line 2003, in unscale_gradients
    self.scaler.unscale_(opt)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 284, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 212, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.

报错如上，我在v100上运行chatglm3-6B的lora sft.sh时弹出这个，都是原始参数，没有修改，正常的下载模型和数据集。

**Comment by Jintao-Huang** [comment]
我这里复现了, 感谢. 我们会在今天进行修复.

**Comment by Jintao-Huang** [comment]
已经修复了❤️, 再次感谢你的发现
