### ISSUE TITLE
Qwen-Audio-Chat微调报错

### ISSUE THREAD

**Issue by lucky-dreamer-nn** [modelscope/swift#234]
您好，拉取最新的代码，peft版本0.7.0，运行 bash scripts/qwen_audio_chat/lora/sft.sh和 bash scripts/qwen_audio_chat/lora_ddp_ds/sft.sh 时出现相同的报错：
Traceback (most recent call last):
  File "llm_sft.py", line 7, in <module>
    output = sft_main()
  File "/datalocal/swift-new/swift/swift/utils/run_utils.py", line 27, in x_main
    return llm_x(args, **kwargs)
  File "/datalocal/swift-new/swift/swift/llm/sft.py", line 96, in llm_sft
    model = Swift.prepare_model(model, lora_config)
  File "/datalocal/swift-new/swift/swift/tuners/base.py", line 511, in prepare_model
    return SwiftModel(model, config, **kwargs)
  File "/datalocal/swift-new/swift/swift/tuners/base.py", line 52, in __init__
    self.adapters[DEFAULT_ADAPTER] = self._prepare_model(
  File "/datalocal/swift-new/swift/swift/tuners/base.py", line 313, in _prepare_model
    return adatper_cls.prepare_model(model, config, adapter_name)
  File "/datalocal/swift-new/swift/swift/tuners/lora.py", line 53, in prepare_model
    LoraModel(model, config, adapter_name)
  File "/datalocal/swift-new/swift/swift/tuners/lora_layers.py", line 206, in __init__
    super().__init__(model, config, adapter_name)
  File "/root/anaconda3/envs/modelscope/lib/python3.8/site-packages/peft/tuners/lora/model.py", line 119, in __init__
    super().__init__(model, config, adapter_name)
  File "/root/anaconda3/envs/modelscope/lib/python3.8/site-packages/peft/tuners/tuners_utils.py", line 95, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/datalocal/swift-new/swift/swift/tuners/lora_layers.py", line 280, in inject_adapter
    self._mark_only_adapters_as_trainable(self.model)
TypeError: _mark_only_adapters_as_trainable() takes 1 positional argument but 2 were given

**Comment by Jintao-Huang** [comment]
你先升级到0.7.1

**Comment by tastelikefeet** [comment]
已经修改requirements
