### ISSUE TITLE
windows上微调报错，麻烦帮忙看看怎么解决

### ISSUE THREAD

**Issue by developer-r2tech** [modelscope/swift#28]
Traceback (most recent call last):
  File "H:\ai\qwen\swift\examples\pytorch\llm\src\llm_sft.py", line 321, in <module>
    llm_sft(args)
  File "H:\ai\qwen\swift\examples\pytorch\llm\src\llm_sft.py", line 299, in llm_sft
    trainer.train(trainer_args.resume_from_checkpoint)
  File "C:\Python310\lib\site-packages\transformers\trainer.py", line 1539, in train
    return inner_training_loop(
  File "C:\Python310\lib\site-packages\transformers\trainer.py", line 1787, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "C:\Python310\lib\site-packages\accelerate\data_loader.py", line 381, in __iter__
Traceback (most recent call last):
    dataloader_iter = super().__iter__()
  File "<string>", line 1, in <module>
  File "C:\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "C:\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 386, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
  File "C:\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 1058, in __init__
    exitcode = _main(fd, parent_sentinel)
  File "C:\Python310\lib\multiprocessing\spawn.py", line 126, in _main
    w.start()
  File "C:\Python310\lib\multiprocessing\process.py", line 121, in start
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
    self._popen = self._Popen(self)
  File "C:\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python310\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Python310\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Python310\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'builtins.CoreBPE' object
  0%|                                                                                            | 0/3 [00:06<?, ?it/s]

**Comment by Jintao-Huang** [comment]
请问你使用的是哪个模型, 什么微调方法等, 我需要复现一下. sh脚本方便发一下嘛

**Comment by developer-r2tech** [comment]
qwen-7b-chat模型，就用的examples\pytorch\llm\scripts\qwen_7b_chat\qlora\sft.sh这个脚本

**Comment by Jintao-Huang** [comment]
你试试将 Seq2SeqTrainingArguments中的dataloader_num_workers=0.

**Comment by developer-r2tech** [comment]
可以了，感谢
