### ISSUE TITLE
show_freeze_layers

### ISSUE THREAD

**Issue by Years-Enron** [modelscope/swift#31]
```
bash scripts/qwen_7b_chat/qlora/sft.sh 
```

```
2023-08-24 13:38:40,885 - modelscope - INFO - PyTorch version 2.0.1 Found.
2023-08-24 13:38:40,886 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-08-24 13:38:40,908 - modelscope - INFO - Loading done! Current index file version is 1.8.4, with md5 1cad0e50ca2a3cb304bd047cd1c5803f and a total number of 902 components indexed
Traceback (most recent call last):
  File "/root/swift/examples/pytorch/llm/src/llm_sft.py", line 10, in <module>
    from utils import (DATASET_MAPPING, MODEL_MAPPING, TEMPLATE_MAPPING,
  File "/root/swift/examples/pytorch/llm/src/utils/__init__.py", line 1, in <module>
    from .dataset import DATASET_MAPPING, get_dataset, process_dataset
  File "/root/swift/examples/pytorch/llm/src/utils/dataset.py", line 9, in <module>
    from swift.utils import get_seed
  File "/opt/conda/lib/python3.10/site-packages/swift/__init__.py", line 4, in <module>
    from .utils.import_utils import _LazyModule
  File "/opt/conda/lib/python3.10/site-packages/swift/utils/__init__.py", line 4, in <module>
    from .torch_utils import (add_version_to_work_dir, get_seed, is_master,
ImportError: cannot import name 'show_freeze_layers' from 'swift.utils.torch_utils' (/opt/conda/lib/python3.10/site-packages/swift/utils/torch_utils.py)
```

看着像代码漏提交了

**Comment by Jintao-Huang** [comment]
该函数已经被废弃了, 使用show_layers函数.  你尝试更新一下代码.

**Comment by Jintao-Huang** [comment]
我发现这个问题了...抱歉

**Comment by Jintao-Huang** [comment]
已经修复了
