### ISSUE TITLE
finetuing with KeyError: 'input_ids'

### ISSUE THREAD

**Issue by v-yunbin** [modelscope/swift#368]
commad:
```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

from swift.llm import DatasetName, ModelType, SftArguments, sft_main

sft_args = SftArguments(
    model_type=ModelType.openbuddy_mistral_7b_chat,
    model_cache_dir="models/openbuddy-mistral-7b-chat",
    custom_train_dataset_path="dataset/guanaco_belle_merge_v1.0/train.json",
    eval_steps=5000,
    save_steps=5000,
    train_dataset_sample=-1,
    logging_steps=5,
    output_dir='output',
    lazy_tokenize=True,
    lora_target_modules='ALL',
output = sft_main(sft_args)
best_model_checkpoint = output['best_model_checkpoint']
print(f'best_model_checkpoint: {best_model_checkpoint}')
```

error:
```
Train:   1%|▊                                                                                                         | 344/42940 [50:59<107:29:15,  9.08s/it]Traceback (most recent call last):
  File "finetune.py", line 19, in <module>
    output = sft_main(sft_args)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/swift/utils/run_utils.py", line 31, in x_main
    result = llm_x(args, **kwargs)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/swift/llm/sft.py", line 277, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/swift/trainers/trainers.py", line 44, in train
    super().train(*args, **kwargs)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/transformers/trainer.py", line 1821, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/accelerate/data_loader.py", line 461, in __iter__
    next_batch = next(dataloader_iter)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/swift/llm/utils/template.py", line 361, in data_collator
    input_ids = [torch.tensor(b['input_ids']) for b in batch]
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/swift/llm/utils/template.py", line 361, in <listcomp>
    input_ids = [torch.tensor(b['input_ids']) for b in batch]
KeyError: 'input_ids'

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Train:   1%|          | 344/
```

**Comment by Jintao-Huang** [comment]
fixed
https://github.com/modelscope/swift/pull/369
