### ISSUE TITLE
无法通过 pip 安装（subprocess-exited-with-error）

### ISSUE THREAD

**Issue by unclexiao** [modelscope/swift#420]
## 我的环境
- MacOS：14.2.1
- Python：3.10.10
- Torch：2.2.0

## 我的操作
```shell
pip install ms-swift -U
```

## 错误提示

```shell
Collecting absl-py>=0.4 (from tensorboard->ms-swift)
  Downloading absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting grpcio>=1.48.2 (from tensorboard->ms-swift)
  Downloading grpcio-1.60.1.tar.gz (24.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.8/24.8 MB 494.8 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/tmp/pip-install-12jd68z1/grpcio_348921d2c9444572b658615eaa026560/setup.py", line 93, in <module>
          import commands
        File "/private/tmp/pip-install-12jd68z1/grpcio_348921d2c9444572b658615eaa026560/src/python/grpcio/commands.py", line 31, in <module>
          import support
        File "/private/tmp/pip-install-12jd68z1/grpcio_348921d2c9444572b658615eaa026560/src/python/grpcio/support.py", line 111, in <module>
          errors.CompileError: diagnose_compile_error,
      AttributeError: module 'setuptools.errors' has no attribute 'CompileError'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

```

**Comment by unclexiao** [comment]
## 补充

本身是大前端开发者，有 Android + iOS 完整开发环境，包括 [Swift 编程语言](https://developer.apple.com/cn/swift/)。

是否受此的影响？

```shell
(base) ~ swift --version
Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: x86_64-apple-darwin23.2.0
```

**Comment by Jintao-Huang** [comment]
其实 ms-swift和swift没有关系的

**Comment by Jintao-Huang** [comment]
你用linux呗, 不要用macos
