### ISSUE TITLE
NCCL timeout

### ISSUE THREAD

**Issue by vincent507cpu** [modelscope/swift#429]
请教一下，我在微调chatglm3-6b-32k时出错了：
```
[rank1]:[E ProcessGroupNCCL.cpp:523] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600906 milliseconds before timing out.
[rank1]:[E ProcessGroupNCCL.cpp:537] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank1]:[E ProcessGroupNCCL.cpp:543] To avoid data inconsistency, we are taking the entire process down.
[rank1]:[E ProcessGroupNCCL.cpp:1182] [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600906 milliseconds before timing out.
Exception raised from checkTimeout at /opt/conda/conda-bld/pytorch_1704987280714/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:525 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7ff00c49fd87 in /home/zwj/miniconda3/envs/swift/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1e6 (0x7ff00d638d26 in /home/zwj/miniconda3/envs/swift/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x19d (0x7ff00d63c27d in /home/zwj/miniconda3/envs/swift/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x119 (0x7ff00d63ce79 in /home/zwj/miniconda3/envs/swift/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdbbf4 (0x7ff07af6bbf4 in /home/zwj/miniconda3/envs/swift/bin/../lib/libstdc++.so.6)
frame #5: <unknown function> + 0x76db (0x7ff083f826db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x3f (0x7ff08350661f in /lib/x86_64-linux-gnu/libc.so.6)
```
系统信息：
显卡：两块V100
系统：Ubuntu 18.04
驱动：Driver Version: 515.65.01    CUDA Version: 11.7
torch：2.2.0
deepspeed：0.13.2
如果需要其他信息，请指出。非常感谢您的帮助！

**Comment by vincent507cpu** [comment]
您好，谢谢您的帮助。在输入 `export NCCL_SOCKET_IFNAME=en,eth,em,bond` 后执行脚本，还是报错，错误相同。

**Comment by vincent507cpu** [comment]
根据 https://blog.csdn.net/EstrangedZ/article/details/133822442 的提示，输入 `export NCCL_P2P_LEVEL=NVL` 和 `export NCCL_P2P_DISABLE=1` 后错误仍然存在。

**Comment by Jintao-Huang** [comment]
单卡可以跑嘛

**Comment by vincent507cpu** [comment]
在这个框架下：
```
Traceback (most recent call last):
  File "/home/zwj/GitHub/swift-main/examples/pytorch/llm/llm_sft.py", line 2, in <module>
    import custom
  File "/home/zwj/GitHub/swift-main/examples/pytorch/llm/custom.py", line 10, in <module>
    from swift.llm import (LoRATM, Template, TemplateType, dataset_map,
  File "/home/zwj/GitHub/swift-main/swift/llm/__init__.py", line 5, in <module>
    from .utils import *
  File "/home/zwj/GitHub/swift-main/swift/llm/utils/__init__.py", line 2, in <module>
    from .argument import (AppUIArguments, DeployArguments, DPOArguments,
  File "/home/zwj/GitHub/swift-main/swift/llm/utils/argument.py", line 20, in <module>
    from .dataset import (DATASET_MAPPING, get_custom_dataset, get_dataset,
  File "/home/zwj/GitHub/swift-main/swift/llm/utils/dataset.py", line 25, in <module>
    from .utils import dataset_map, download_dataset
  File "/home/zwj/GitHub/swift-main/swift/llm/utils/utils.py", line 753, in <module>
    if is_ddp_plus_mp():
  File "/home/zwj/GitHub/swift-main/swift/utils/torch_utils.py", line 114, in is_ddp_plus_mp
    if not is_mp():
  File "/home/zwj/GitHub/swift-main/swift/utils/torch_utils.py", line 105, in is_mp
    assert n_gpu % local_world_size == 0
AssertionError
```
在其他脚本里爆显存

**Comment by Jintao-Huang** [comment]
n_gpu % local_world_size == 0 代表 gpu数与进程数 除不尽. 你是几张卡的环境, sh发一下吧

**Comment by vincent507cpu** [comment]
机器上有8张V100，但是nproc_per_node取8会报错，现在我取4

**Comment by vincent507cpu** [comment]
不知道怎么的，问题突然没有了。。。谢谢了
