### ISSUE TITLE
qwen-vl-chat微调时有图片大小要求吗，微调CogVLM-SFT-311K报错

### ISSUE THREAD

**Issue by xs818818** [modelscope/swift#453]
Traceback (most recent call last):
  File "/workspace/llm_train/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/workspace/llm_train/swift/utils/run_utils.py", line 31, in x_main
    result = llm_x(args, **kwargs)
  File "/workspace/llm_train/swift/llm/sft.py", line 148, in llm_sft
    train_dataset = dataset_map(train_dataset, template.encode,
  File "/workspace/llm_train/swift/llm/utils/utils.py", line 271, in dataset_map
    d = single_map(d)
  File "/workspace/llm_train/swift/llm/utils/utils.py", line 220, in _single_map
    d = map_func(d)
  File "/workspace/llm_train/swift/llm/utils/template.py", line 213, in encode
    inputs, tokenizer_kwargs = self._encode(query, response, history,
  File "/workspace/llm_train/swift/llm/utils/template.py", line 348, in _encode
    input_ids, labels, loss_scale, tokenizer_kwargs = self._encode_context_list(
  File "/workspace/llm_train/swift/llm/utils/template.py", line 296, in _encode_context_list
    token_list = tokenizer(
  File "/opt/conda/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2803, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2909, in _call_one
    return self.encode_plus(
  File "/opt/conda/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2982, in encode_plus
    return self._encode_plus(
  File "/opt/conda/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 719, in _encode_plus
    first_ids = get_input_ids(text)
  File "/opt/conda/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 686, in get_input_ids
    tokens = self.tokenize(text, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/tokenization_qwen.py", line 292, in tokenize
    return _replace_closed_tag(tokens, self.image_start_tag, self.image_end_tag, _encode_imgurl)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/tokenization_qwen.py", line 94, in _replace_closed_tag
    raise ValueError("Unclosed image token")
ValueError: Unclosed image token

**Comment by xs818818** [comment]
主要是我查不出是那一张图片有问题

**Comment by Jintao-Huang** [comment]
![image](https://github.com/modelscope/swift/assets/45290347/b0f6792c-d2a3-4a9f-a432-b756e1d8f050)

感觉是格式不对

**Comment by Jintao-Huang** [comment]
这个报错 感觉是 有些response只有<img> 没有 </img>造成的.

**Comment by Jintao-Huang** [comment]
打错了. 有些response中 </img>缺失造成的

**Comment by Jintao-Huang** [comment]
`</img>`
