### ISSUE TITLE
vllm 推理qwen 72B报错

### ISSUE THREAD

**Issue by zhangfan-algo** [modelscope/swift#527]
推理脚本
RAY_memory_monitor_refresh_ms=0 CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python examples/pytorch/llm/llm_infer.py \
    --infer_backend vllm \
    --ckpt_dir /mnt/pfs/zhangfan/study_info/LLaMA-Factory_0308/output/study_info_cit_stage2_qwen1half5_14B_0308/checkpoint-800 \
    --custom_val_dataset_path data/all_original_prompts_0308_3W_swift_test.jsonl \
    --max_length 9800 \
    --use_flash_attn true \
    --max_new_tokens 2048 \
    --temperature 0.01 \
    --top_p 0.99 \
    --repetition_penalty 1. \
    --use_flash_attn true \
    --verbose false \
    --do_sample true \
    --val_dataset_sample -1 \
    --tensor_parallel_size 100 

报错：

Traceback (most recent call last):
  File "/mnt/pfs/zhangfan/study_info/swift_0311/examples/pytorch/llm/llm_infer.py", line 7, in <module>
    result = infer_main()
  File "/mnt/pfs/zhangfan/study_info/swift/swift/utils/run_utils.py", line 31, in x_main
    result = llm_x(args, **kwargs)
  File "/mnt/pfs/zhangfan/study_info/swift/swift/llm/infer.py", line 215, in llm_infer
    llm_engine, template = prepare_vllm_engine_template(args)
  File "/mnt/pfs/zhangfan/study_info/swift/swift/llm/utils/vllm_utils.py", line 339, in prepare_vllm_engine_template
    llm_engine = get_vllm_engine(
  File "/mnt/pfs/zhangfan/study_info/swift/swift/llm/utils/vllm_utils.py", line 77, in get_vllm_engine
    llm_engine = llm_engine_cls.from_engine_args(engine_args)
  File "/mnt/pfs/zhangfan/system/anaconda/envs/swift/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 389, in from_engine_args
    placement_group = initialize_cluster(parallel_config)
  File "/mnt/pfs/zhangfan/system/anaconda/envs/swift/lib/python3.10/site-packages/vllm/engine/ray_utils.py", line 129, in initialize_cluster
    raise ValueError(
ValueError: The number of required GPUs exceeds the total number of available GPUs in the cluster.

**Comment by Jintao-Huang** [comment]
--tensor_parallel_size 8

**Comment by Jintao-Huang** [comment]
可以看一下这里:
https://github.com/modelscope/swift/blob/main/docs/source/LLM/Qwen1.5%E5%85%A8%E6%B5%81%E7%A8%8B%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md#%E6%8E%A8%E7%90%86-1

**Comment by zhangfan-algo** [comment]
![image](https://github.com/modelscope/swift/assets/47747764/2ed0a74f-3e28-45c7-86e2-aaff9529f311)
喂给模型的数据没有None的 但是生产的responese有None

**Comment by Jintao-Huang** [comment]
--max_length -1

**Comment by zhangfan-algo** [comment]
可以了感谢

**Comment by Jintao-Huang** [comment]
--max_length -1 已经设置为推理时候的默认值
