### ISSUE TITLE
AttributeError: 'MsDataset' object has no attribute 'info'

### ISSUE THREAD

**Issue by liuzhengzheng123** [modelscope/swift#58]
Traceback (most recent call last):
  File "/data/home/tgyhyt/project/swift-main/examples/pytorch/llm/src/llm_sft.py", line 338, in <module>
    llm_sft(args)
  File "/data/home/tgyhyt/project/swift-main/examples/pytorch/llm/src/llm_sft.py", line 230, in llm_sft
    dataset = get_dataset(args.dataset.split(','))
  File "/data/home/tgyhyt/project/swift-main/examples/pytorch/llm/src/utils/dataset.py", line 339, in get_dataset
    dataset_list.append(get_function())
  File "/data/home/tgyhyt/project/swift-main/examples/pytorch/llm/src/utils/dataset.py", line 181, in get_coco_en_dataset
    return _process_mutimodal_dataset(dataset, 'please describe the image', 'image', 'caption')
  File "/data/home/tgyhyt/project/swift-main/examples/pytorch/llm/src/utils/dataset.py", line 152, in _process_mutimodal_dataset
    dataset.features._column_requires_decoding['image'] = False
AttributeError: 'MsDataset' object has no attribute 'info'

**Comment by Jintao-Huang** [comment]
我没有复现这个问题诶, 你试试更新一下modelscope, transformers, datasets
