### ISSUE TITLE
v100单卡lora微调qwen-vl-chat报错

### ISSUE THREAD

**Issue by shikimoon** [modelscope/swift#625]
运行脚本CUDA_VISIBLE_DEVICES=0 swift sft --model_type qwen-vl-chat --model_id_or_path /root/youyun.ke/qwen-vl/model --dataset coco-mini-en --output_dir lora_test
报错信息
[ERROR:swift] Authentication token does not exist, failed to access model unknown which may not exist or may be                 private. Please login first.
[ERROR:swift] Authentication token does not exist, failed to access model unknown which may not exist or may be                 private. Please login first.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/usr/local/lib/python3.8/dist-packages/swift/utils/run_utils.py", line 31, in x_main
    result = llm_x(args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/swift/llm/sft.py", line 212, in llm_sft
    trainer = Seq2SeqTrainer(
  File "/usr/local/lib/python3.8/dist-packages/swift/trainers/trainers.py", line 36, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/swift/trainers/mixin.py", line 283, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer_seq2seq.py", line 56, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 367, in __init__
    self.create_accelerator_and_postprocess()
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 4127, in create_accelerator_and_postprocess
    self.accelerator = Accelerator(
TypeError: __init__() got an unexpected keyword argument 'use_seedable_sampler'
用的官方示例安装的环境pip install ms-swift[all] -U

**Comment by tastelikefeet** [comment]
更新下accelerate 版本

**Comment by shikimoon** [comment]
> 更新下accelerate 版本

已经解决。谢谢
