### ISSUE TITLE
IndexError: index 0 is out of bounds for dimension 0 with size 0

### ISSUE THREAD

**Issue by JackHenry1992** [modelscope/swift#63]
训练百川2-7b报这个错误，
数据集是我自己的，可以使用qwen-7b-lora-ddp脚本训练，但是百川训练会报错（配置使用的下载下来默认的）

```
IndexError: index 0 is out of bounds for dimension 0 with size 0
    output_dir = broadcast_string(output_dir)    
first_zero = (tensor == 0).nonzero()[0].item()  File "examples/pytorch/llm/src/utils/utils.py", line 181, in broadcast_string

IndexError: index 0 is out of bounds for dimension 0 with size 0
    first_zero = (tensor == 0).nonzero()[0].item()
IndexError: index 0 is out of bounds for dimension 0 with size 0
Traceback (most recent call last):
  File "examples/pytorch/llm/src/llm_sft.py", line 345, in <module>
    llm_sft(args)
  File "examples/pytorch/llm/src/llm_sft.py", line 255, in llm_sft
    output_dir = broadcast_string(output_dir)
  File "examples/pytorch/llm/src/utils/utils.py", line 181, in broadcast_string
    first_zero = (tensor == 0).nonzero()[0].item()
IndexError: index 0 is out of bounds for dimension 0 with size 0
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2720322 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2720323 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2720318) of binary: /mnt/data1/yingzhi/dlframework/miniconda3/envs/pygpt/bin/python
Traceback (most recent call last):
  File "/mnt/data1/yingzhi/dlframework/miniconda3/envs/pygpt/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/llm_sft.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-09-09_21:53:07
  host      : ubuntu-4U-GPU-Server
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2720319)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-09-09_21:53:07
  host      : ubuntu-4U-GPU-Server
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 2720320)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-09-09_21:53:07
  host      : ubuntu-4U-GPU-Server
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 2720321)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-09_21:53:07
  host      : ubuntu-4U-GPU-Server
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2720318)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

**Comment by JackHenry1992** [comment]
训练qwen-7b-chat版本也有这个错误

**Comment by Jintao-Huang** [comment]
应该是buffer_size太小的, 然后文件名路径太长了. 我这里增加一下, 默认的buffer_size变成200.
