### ISSUE TITLE
 raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)

### ISSUE THREAD

**Issue by JackHenry1992** [modelscope/swift#64]
训练qwen_7b/lora_ddp/sft.sh，训练一段时间后，会出现下面的错误，而且看起来是已经训练超过1个epoch了，数据集说明已经训练一遍了，那是什么原因呀？

```
12%|█▏        | 2899/25120 [2:12:20<16:58:37,  2.75s/it]
 12%|█▏        | 2900/25120 [2:12:23<16:39:43,  2.70s/it]
                                                         
{'loss': 2.011, 'learning_rate': 9.81e-05, 'epoch': 1.85, 'global_step': 2900}

 12%|█▏        | 2900/25120 [2:12:23<16:39:43,  2.70s/it]
 12%|█▏        | 2900/25120 [2:12:23<16:39:43,  2.70s/it]
 12%|█▏        | 2901/25120 [2:12:26<16:59:40,  2.75s/it]
 12%|█▏        | 2902/25120 [2:12:28<16:18:49,  2.64s/it]
 12%|█▏        | 2903/25120 [2:12:31<16:37:35,  2.69s/it]
 12%|█▏        | 2904/25120 [2:12:34<16:56:03,  2.74s/it]
 12%|█▏        | 2905/25120 [2:12:37<17:37:09,  2.86s/it]WARNING:torch.distributed.elastic.agent.server.api:Received 1 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2919043 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2919044 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2919045 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2919046 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2919047 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2919048 closing signal SIGHUP
Traceback (most recent call last):
  File "miniconda3/envs/pygpt/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 241, in launch_agent
    result = agent.run()
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 723, in run
    result = self._invoke_run(role)
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 864, in _invoke_run
    time.sleep(monitor_interval)
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 2918977 got signal: 1
```

**Comment by Jintao-Huang** [comment]
我感觉像是内存炸了, 不然应该会有报错的提示

**Comment by JackHenry1992** [comment]
但是已经跑完了完整的epoch训练诶，而且好像是随机出现的？有时候是2个epoch。
我是单机八卡A100，用了其中6张卡训练，是要改小batchsize再试试吗？

```
 16%|█▌        | 4075/25120 [3:01:57<16:11:36,  2.77s/it]
 16%|█▌        | 4076/25120 [3:02:00<16:52:08,  2.89s/it]
 16%|█▌        | 4077/25120 [3:02:03<15:48:59,  2.71s/it]
 16%|█▌        | 4078/25120 [3:02:05<15:34:31,  2.66s/it]
 16%|█▌        | 4079/25120 [3:02:08<15:17:58,  2.62s/it]
 16%|█▌        | 4080/25120 [3:02:10<15:17:25,  2.62s/it]
                                                         
{'loss': 2.2907, 'learning_rate': 9.547e-05, 'epoch': 2.6, 'global_step': 4080}

 16%|█▌        | 4080/25120 [3:02:10<15:17:25,  2.62s/it]
 16%|█▌        | 4080/25120 [3:02:10<15:17:25,  2.62s/it]
 16%|█▌        | 4081/25120 [3:02:14<16:17:39,  2.79s/it]
 16%|█▋        | 4082/25120 [3:02:16<16:18:54,  2.79s/it]
 16%|█▋        | 4083/25120 [3:02:19<16:33:47,  2.83s/it]
 16%|█▋        | 4084/25120 [3:02:22<16:20:02,  2.80s/it]WARNING:torch.distributed.elastic.agent.server.api:Received 1 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2973583 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2973584 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2973585 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2973586 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2973587 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2973588 closing signal SIGHUP
Traceback (most recent call last):
  File "miniconda3/envs/pygpt/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 241, in launch_agent
    result = agent.run()
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 723, in run
    result = self._invoke_run(role)
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 864, in _invoke_run
    time.sleep(monitor_interval)
  File "miniconda3/envs/pygpt/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 2973491 got signal: 
```

**Comment by Jintao-Huang** [comment]
我猜测是内存 (不是显存)不够的原因. 你降低batch_size试试呗

**Comment by PANHAOC** [comment]
你好，请问解决了吗？我也遇到这个问题了
