### ISSUE TITLE
KeyError: 'export'

### ISSUE THREAD

**Issue by ArlanCooper** [modelscope/swift#652]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
运行官方的量化脚本:
```
CUDA_VISIBLE_DEVICES=3 swift export \
    --model_type qwen1half-14b-chat --quant_bits 8 \
	--model_cache_dir /data/share/rwq/Qwen1.5-14B-Chat_lora
    --custom_train_dataset_path /home/powerop/work/rwq/email_classify/extract_info/data/swift_train.jsonl \
    --quant_method gptq \
	--quant_seqlen 4096


```
报错信息:
```
Traceback (most recent call last):
  File "/home/powerop/work/conda/envs/swift/bin/swift", line 8, in <module>
    sys.exit(cli_main())
  File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/swift/cli/main.py", line 50, in cli_main
    file_path = importlib.util.find_spec(ROUTE_MAPPING[method_name]).origin
KeyError: 'export'


```
提示没有export命令。

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

cuda版本: 12.2
torch版本: 2.1.2+cu121
swift版本:1.6.1

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
`pip install ms-swift[llm]`或者直接使用main分支

**Comment by ArlanCooper** [comment]
> `pip install ms-swift[llm]`或者直接使用main分支

我这按安装是全部的包，pip install ms-swift[all] -U

**Comment by Jintao-Huang** [comment]
都可以的  swift==1.6.1太老了

**Comment by ArlanCooper** [comment]
好滴，我这边更新版本之后是可以的，但是，我这边使用gptq量化的时候，为什么指定自定义训练集，不管用，还是走到了默认的dataset数据集了呢？
```
CUDA_VISIBLE_DEVICES=1 swift export \
    --model_type qwen1half-14b-chat --quant_bits 4 \
	--model_cache_dir /data/share/rwq/Qwen1.5-14B-Chat
    --custom_train_dataset_path /home/powerop/work/rwq/swift_train.jsonl \
    --quant_method gptq \
	--quant_seqlen 4096

```


但是运行显示参数:
```
 args: ExportArguments(model_type='qwen1half-14b-chat', model_id_or_path='/data/share/rwq/Qwen1.5-14B-Chat_lora', model_revision='master', sft_type='full', template_type='qwen', infer_backend='pt', ckpt_dir=None, load_args_from_ckpt_dir=False, load_dataset_config=False, eval_human=True, seed=42, dtype='AUTO', dataset=['ms-bench-mini'], dataset_seed=42, dataset_test_ratio=0.01, val_dataset_sample=10, save_result=True, system=None, max_length=None, truncation_strategy='delete', check_dataset_strategy='none', custom_train_dataset_path=[], custom_val_dataset_path=[], quantization_bit=0, bnb_4bit_comp_dtype='AUTO', bnb_4bit_quant_type='nf4', bnb_4bit_use_double_quant=True, max_new_tokens=2048, do_sample=True, temperature=0.3, top_k=20, top_p=0.7, repetition_penalty=1.0, num_beams=1, stop_words=None, use_flash_attn=None, ignore_args_error=False, stream=True, merge_lora=False, merge_device_map='cpu', save_safetensors=True, overwrite_generation_config=False, verbose=None, gpu_memory_utilization=0.9, tensor_parallel_size=1, max_model_len=None, vllm_enable_lora=False, vllm_max_lora_rank=16, vllm_lora_modules=[], show_dataset_sample=10, safe_serialization=None, model_cache_dir=None, merge_lora_and_save=None, to_peft_format=False, quant_bits=8, quant_method='awq', quant_n_samples=256, quant_seqlen=2048, quant_device_map='cpu', push_to_hub=False, hub_model_id=None, hub_token=None, hub_private_repo=False, commit_message='update files')
[INFO:swift] Setting args.torch_dtype: torch.float16

```

显示：dataset=['ms-bench-mini'],
而custom_train_dataset_path 是空的



我这边更新swift版本是：ms-swift    1.8.0.dev0   /home/powerop/work/rwq/swift

**Comment by ArlanCooper** [comment]
> 都可以的 swift==1.6.1太老了

好滴，我这边更新swift版本是：ms-swift 1.8.0.dev0，已经没问题了，感谢
