### ISSUE TITLE
微调千问1.5-MoE-A2.7B-Chat报错NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by trunks023** [modelscope/swift#653]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
我的操作过程如下
**1. 下载模型，方式如下：**
```
from modelscope import snapshot_download
# model_dir = snapshot_download('/output/Qwen1.5-MoE-A2.7B-Chat')
snapshot_download('qwen/Qwen1.5-MoE-A2.7B-Chat', cache_dir='/output/qwen1.5-MoE/Qwen1.5-MoE-A2.7B-Chat')
```
**2.安装swift**
```
pip install ms-swift[llm] -U
```

**3.安装transformer和flash_attn**
```
pip install git+https://github.com/huggingface/transformers
pip install flash_attn
```

**4.修改微调脚本** /swift/examples/pytorch/llm/scripts/qwen1half_moe_a2_7b_chat/lora/sft.sh 
```
# you will have to install transformers from source
# pip install git+https://github.com/huggingface/transformers
# Experimental environment: A100
# 42GB GPU memory
PYTHONPATH=../../.. \
CUDA_VISIBLE_DEVICES=0 \
python llm_sft.py \
    --model_type qwen1half-moe-a2_7b-chat \
    --model_id_or_path /input0/Qwen1.5-MoE-A2.7B-Chat \
    --sft_type lora \
    --tuner_backend peft \
    --dtype AUTO \
    --output_dir output \
    --dataset /output/ft_data/pca_ft_train_1_5_swift.jsonl \
    --train_dataset_sample -1 \
    --num_train_epochs 1 \
    --max_length 1024 \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules ALL \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0.1 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 16 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --use_flash_attn true \
```

**5.执行微调**
```
/output/swift/examples/pytorch/llm# sh scripts/qwen1half_moe_a2_7b_chat/lora/sft.sh
```

**6.执行过程报错：**
```
[ERROR:swift] Authentication token does not exist, failed to access model qwen/Qwen1___5-MoE-A2___7B-Chat which may not exist or may be                 private. Please login first.
[ERROR:swift] Authentication token does not exist, failed to access model qwen/Qwen1___5-MoE-A2___7B-Chat which may not exist or may be                 private. Please login first.
Traceback (most recent call last):
  File "/output/swift/examples/pytorch/llm/llm_sft.py", line 7, in <module>
    output = sft_main()
  File "/output/swift/swift/utils/run_utils.py", line 31, in x_main
    result = llm_x(args, **kwargs)
  File "/output/swift/swift/llm/sft.py", line 203, in llm_sft
    trainer = Seq2SeqTrainer(
  File "/output/swift/swift/trainers/trainers.py", line 36, in __init__
    super().__init__(*args, **kwargs)
  File "/output/swift/swift/trainers/mixin.py", line 283, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/transformers/trainer_seq2seq.py", line 57, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/transformers/trainer.py", line 499, in __init__
    self._move_model_to_device(model, args.device)
  File "/usr/local/lib/python3.10/site-packages/transformers/trainer.py", line 740, in _move_model_to_device
    model = model.to(device)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 5 more times]
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

```
**nvcc --version**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0


**uname -a**
Linux cf9yunid7u5-p28ml9xubmvz-main 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**nvidia-smi**
Wed Apr  3 03:08:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:25:00.0 Off |                  Off |
| 30%   30C    P8              19W / 450W |      3MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

**print(torch.__version__)**
2.1.0+cu121

```

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by trunks023** [comment]
看了一下？这个MoE-A2.7B-Chat微调需要接近42G的显存？

**Comment by trunks023** [comment]
好了，我知道了，是显存不够，换了张A6000的卡，可以微调了，虽然推理消耗的显存少，但是微调对显存的要求还是蛮高的。
```
(base) root@cf9yunid7u5-p28ml9xubmvz-main:/openbayes/home# nvidia-smi
Wed Apr  3 07:01:41 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.146.02             Driver Version: 535.146.02   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A6000               On  | 00000000:4B:00.0 Off |                  Off |
| 30%   36C    P2              80W / 300W |  34387MiB / 49140MiB |     18%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
```

**Comment by 1028686314** [comment]
> > 看了一下？这个MoE-A2.7B-Chat微调需要接近42G的显存？
> 
> 原模型总参数量14.3b，资源消耗可以参考脚本上的数据

老师 我也遇到了类似的问题 我是sft internvl-chat-v1.5
Traceback (most recent call last):
  File "/mnt/workspace/workgroup/bolin/swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/mnt/workspace/workgroup/bolin/swift/swift/utils/run_utils.py", line 27, in x_main
    result = llm_x(args, **kwargs)
  File "/mnt/workspace/workgroup/bolin/swift/swift/llm/sft.py", line 274, in llm_sft
    trainer = Seq2SeqTrainer(
  File "/mnt/workspace/workgroup/bolin/swift/swift/trainers/trainers.py", line 36, in __init__
    super().__init__(*args, **kwargs)
  File "/mnt/workspace/workgroup/bolin/swift/swift/trainers/mixin.py", line 241, in __init__
    super().__init__(
  File "/home/pai/lib/python3.9/site-packages/transformers/trainer_seq2seq.py", line 57, in __init__
    super().__init__(
  File "/home/pai/lib/python3.9/site-packages/transformers/trainer.py", line 528, in __init__
    self._move_model_to_device(model, args.device)
  File "/home/pai/lib/python3.9/site-packages/transformers/trainer.py", line 775, in _move_model_to_device
    model = model.to(device)
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 6 more times]
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

但是我用的是两张a100呀 这个是为什么呢
<img width="861" alt="image" src="https://github.com/modelscope/swift/assets/38694780/69f5f107-6227-49b7-b618-817fefc52483">
