### ISSUE TITLE
4张显卡同时运行，但无法跑满，最终报错

### ISSUE THREAD

**Issue by dunbin** [modelscope/swift#673]
**这是我的参数配置*
运行后会执行几分钟，然后报错停止。检查现存也看到没有跑满，请问是什么问题。
CUDA_VISIBLE_DEVICES=0,1,2,3 \
swift sft \
    --model_type qwen1half-7b-chat \
    --sft_type lora \
    --tuner_backend swift \
    --dtype AUTO \
    --output_dir output \
    --custom_train_dataset_path /home/neobin/Documents/swift/xinde.jsonl \
    --train_dataset_sample 5000 \
    --num_train_epochs 50 \
    --max_length 1024 \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules ALL \
    --gradient_checkpointing true \
    --batch_size 24 \
    --weight_decay 0.1 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 16 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 50 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --use_flash_attn false \
    --self_cognition_sample 1000 \
    --model_name xingyun \
    --model_author ertingxihu \

**按照官方配置安装**
accelerate
dacite
datasets
jieba
matplotlib
modelscope>=1.13.3
nltk
numpy
optimum>=1.17.0
pandas
peft>=0.9.0,<0.10.0
requests
rouge
safetensors
tensorboard
tqdm
transformers>=4.33,<4.41
transformers_stream_generator
trl>=0.7.7

**Additional context**
[ERROR:swift] Authentication token does not exist, failed to access model qwen/Qwen1___5-7B-Chat which may not exist or may be                 private. Please login first.
[ERROR:swift] Authentication token does not exist, failed to access model qwen/Qwen1___5-7B-Chat which may not exist or may be                 private. Please login first.
/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/accelerate/accelerator.py:436: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
[INFO:swift] The SftArguments will be saved in: /home/neobin/Documents/swift/output/qwen1half-7b-chat/v0-20240409-135758/sft_args.json
[INFO:swift] The Seq2SeqTrainingArguments will be saved in: /home/neobin/Documents/swift/output/qwen1half-7b-chat/v0-20240409-135758/training_args.json
[INFO:swift] The logging file will be saved in: /home/neobin/Documents/swift/output/qwen1half-7b-chat/v0-20240409-135758/logging.jsonl
Train:   0%|          | 1/250 [02:04<8:36:55, 124.56s/it]{'loss': 7.85501337, 'acc': 0.1831516, 'grad_norm': 22.36450768, 'learning_rate': 1.25e-05, 'epoch': 0.18, 'global_step': 1}
Traceback (most recent call last):
  File "/home/neobin/Documents/swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/home/neobin/Documents/swift/swift/utils/run_utils.py", line 31, in x_main
    result = llm_x(args, **kwargs)
  File "/home/neobin/Documents/swift/swift/llm/sft.py", line 229, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/home/neobin/Documents/swift/swift/trainers/trainers.py", line 50, in train
    res = super().train(*args, **kwargs)
  File "/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 1780, in train
    return inner_training_loop(
  File "/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 2118, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 3036, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/neobin/Documents/swift/swift/trainers/trainers.py", line 216, in compute_loss
    outputs = model(**inputs)
  File "/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 825, in forward
    return model_forward(*args, **kwargs)
  File "/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 813, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/neobin/Documents/swift/swift/tuners/base.py", line 84, in forward
    return self.base_model(*args, **kwargs)
  File "/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1200, in forward
    loss = loss_fct(shift_logits, shift_labels)
  File "/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 1179, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/neobin/anaconda3/envs/swift/lib/python3.10/site-packages/torch/nn/functional.py", line 3059, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by dunbin** [comment]
您好！信件已收到，感谢您的来信。

**Comment by gengpeip** [comment]
> 在最前面 加上 NPROC_PER_NODE=2 或着 NPROC_PER_NODE=4

您好，我和楼主遇到了相同的问题，在添加 NPROC_PER_NODE 之后会报显存不足，应该怎么办呢？

**Comment by gengpeip** [comment]
> 在最前面 加上 NPROC_PER_NODE=2 或着 NPROC_PER_NODE=4

CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=0,1,2,3  swift sft --model  DeepSeek-R1-Distill-Qwen-7B --train_type lora --dataset 'unsloth/medical_data.json'  --torch_dtype float16 --num_train_epochs 1 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --learning_rate 1e-4 --lora_rank 8 --lora_alpha 32 --target_modules all-linear --gradient_accumulation_steps 16 --eval_steps 50 --save_steps 50 --save_total_limit 5 --logging_steps 5 --max_length 2048 --output_dir output     --warmup_ratio 0.05 --dataloader_num_workers 4 
我加上了CUDA_LAUNCH_BLOCKING=1这个之后，完成了50次迭代和一次验证，目前还没出现问题，但是速度相对较慢，显存占用情况如下

![Image](https://github.com/user-attachments/assets/511dd00e-3013-4703-b9a0-3d5e4c1272a5)
