### ISSUE TITLE
eval 模式对显存的要求很高的样子

### ISSUE THREAD

**Issue by kratorado** [modelscope/swift#694]
**Describe the bug**
## 命令
```bash
CUDA_VISIBLE_DEVICES=0,1,2,3 swift eval     \
--model_type "qwen1half-14b-chat-int4"     \
--infer_backend vllm \
--tensor_parallel_size 4
```
## 输出
```bash
Traceback (most recent call last):
  File "~/work/swift/swift/swift/cli/eval.py", line 5, in <module>
    eval_main()
  File "~/work/swift/swift/swift/utils/run_utils.py", line 31, in x_main
    result = llm_x(args, **kwargs)
  File "~/work/swift/swift/swift/llm/eval.py", line 150, in llm_eval
    run_eval_single_model(args, model_name)
  File "~/work/swift/swift/swift/llm/eval.py", line 119, in run_eval_single_model
    eval_model = EvalModel(args, model_name, config=record or {})
  File "~/work/swift/swift/swift/llm/eval.py", line 23, in __init__
    self.llm_engine, self.template = prepare_vllm_engine_template(args)
  File "~/work/swift/swift/swift/llm/utils/vllm_utils.py", line 406, in prepare_vllm_engine_template
    llm_engine = get_vllm_engine(
  File "~/work/swift/swift/swift/llm/utils/vllm_utils.py", line 98, in get_vllm_engine
    llm_engine = llm_engine_cls.from_engine_args(engine_args)
  File "~/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 196, in from_engine_args
    engine = cls(
  File "~/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 110, in __init__
    self.model_executor = executor_class(model_config, cache_config,
  File "~/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/executor/ray_gpu_executor.py", line 65, in __init__
    self._init_cache()
  File "~/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/executor/ray_gpu_executor.py", line 253, in _init_cache
    self._run_workers("warm_up_model")
  File "~/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/executor/ray_gpu_executor.py", line 324, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "~/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/worker/worker.py", line 167, in warm_up_model
    self.model_runner.capture_model(self.gpu_cache)
  File "~/miniconda3/envs/swift/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "~/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 854, in capture_model
    graph_runner.capture(
  File "~/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 919, in capture
    with torch.cuda.graph(self.graph, pool=memory_pool):  # noqa: SIM117
  File "~/miniconda3/envs/swift/lib/python3.10/site-packages/torch/cuda/graphs.py", line 197, in __exit__
    self.cuda_graph.capture_end()
  File "~/miniconda3/envs/swift/lib/python3.10/site-packages/torch/cuda/graphs.py", line 88, in capture_end
    super().capture_end()
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
```

**Your hardware and system info**
V100 32G x 4,  cuda12.1, torch 2.1.2
vllm==0.4.0.post1
swift version == 8727cd323aa598b97650c5e37d374320d69e88ce

**Additional context**
不用vllm作为backend的时候，只有一张显卡在工作
用vllm的时候，把max_model_len调到很低了也会爆显存

**Comment by kratorado** [comment]
把vllm降级到0.3.3，可以了
