### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by SunLang115** [modelscope/swift#769]
(swift) [sunkaijie@localhost swift]$ CUDA_VISIBLE_DEVICES=0 swift infer --model_type llava1d6-mistral-7b-instruct
run sh: `python /home/sunkaijie/project/swift/swift/cli/infer.py --model_type llava1d6-mistral-7b-instruct`
2024-04-22 08:11:33,587 - modelscope - INFO - PyTorch version 2.2.2 Found.
2024-04-22 08:11:33,588 - modelscope - INFO - Loading ast index from /home/sunkaijie/.cache/modelscope/ast_indexer
2024-04-22 08:11:33,621 - modelscope - INFO - Loading done! Current index file version is 1.13.3, with md5 2911bfe27de51af351c02ec5ebb936e7 and a total number of 972 components indexed
[INFO:swift] Start time of running main: 2024-04-22 08:11:33.921263
[INFO:swift] ckpt_dir: None
[INFO:swift] Due to `ckpt_dir` being `None`, `load_args_from_ckpt_dir` is set to `False`.
[INFO:swift] Setting template_type: llava-mistral-instruct
[INFO:swift] Setting self.eval_human: True
[INFO:swift] Setting overwrite_generation_config: False
[INFO:swift] args: InferArguments(model_type='llava1d6-mistral-7b-instruct', model_id_or_path='AI-ModelScope/llava-v1.6-mistral-7b', model_revision='master', sft_type='full', template_type='llava-mistral-instruct', infer_backend='pt', ckpt_dir=None, load_args_from_ckpt_dir=False, load_dataset_config=False, eval_human=True, seed=42, dtype='fp16', dataset=[], dataset_seed=42, dataset_test_ratio=0.01, val_dataset_sample=10, save_result=True, system=None, max_length=None, truncation_strategy='delete', check_dataset_strategy='none', custom_train_dataset_path=[], custom_val_dataset_path=[], quantization_bit=0, bnb_4bit_comp_dtype='fp16', bnb_4bit_quant_type='nf4', bnb_4bit_use_double_quant=True, max_new_tokens=2048, do_sample=True, temperature=0.3, top_k=20, top_p=0.7, repetition_penalty=1.0, num_beams=1, stop_words=None, use_flash_attn=None, ignore_args_error=False, stream=True, merge_lora=False, merge_device_map='cpu', save_safetensors=True, overwrite_generation_config=False, verbose=None, gpu_memory_utilization=0.9, tensor_parallel_size=1, max_model_len=None, vllm_enable_lora=False, vllm_max_lora_rank=16, vllm_lora_modules=[], show_dataset_sample=10, safe_serialization=None, model_cache_dir=None, merge_lora_and_save=None)
[INFO:swift] Global seed set to 42
[INFO:swift] device_count: 1
[INFO:swift] Downloading the model from ModelScope Hub, model_id: AI-ModelScope/llava-v1.6-mistral-7b
Downloading: 100%|████████████████████████████████████████████████████████████████| 1.59k/1.59k [00:00<00:00, 8.77MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 48.0/48.0 [00:00<00:00, 356kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 954kB/s]
Downloading:  92%|██████████████████████████████████████████████████████████▋     | 4.22G/4.60G [02:4Downloading:  93%|███████████████████████████████████████████████████████████▋    | 4.29G/4.60G [02:4Downloading:  97%|█████████████████████████████████████████████████████████████▊  | 4.45G/4.60G [02:4Downloading: 100%|███████████████████████████████████████████████████████████████▉| 4.60G/4.60G [02:4Downloading: 100%|███████████████████████████████████████████████████████████████▉| 4.60G/4.60G [02:49<00:00, 29.1MB/s]
Downloading: 100%|█████████████████████████████████████████████▉| 4.66G/4.66G [02:49<00:00, 29.5MB/s]
Downloading:  65%|█████████████████████████████▊                                                     Downloading: 100%|█████████████████████████████████████████████▉| 4.59G/4.59G [02:34<00:00, 31.9MB/s]
Downloading: 100%|██████████████████████████████████████████| 250M/250M [00:28<00:00, 9.09MB/s]
Downloading: 100%|████████████████████████████████████████| 71.5k/71.5k [00:00<00:00, 1.16MB/s]
Downloading: 100%|████████████████████████████████████████| 1.46k/1.46k [00:00<00:00, 10.2MB/s]
Downloading: 100%|████████████████████████████████████████████| 438/438 [00:00<00:00, 1.47MB/s]
Downloading: 100%|████████████████████████████████████████| 1.71M/1.71M [00:00<00:00, 7.36MB/s]
Downloading: 100%|██████████████████████████████████████████| 482k/482k [00:00<00:00, 2.92MB/s]
Downloading: 100%|████████████████████████████████████████| 1.43k/1.43k [00:00<00:00, 6.43MB/s]
Downloading: 100%|██████████████████████████████████████████| 702k/702k [00:00<00:00, 4.55MB/s]
Downloading: 100%|████████████████████████████████████████| 6.87k/6.87k [00:00<00:00, 40.8MB/s]
[INFO:swift] Run the command: `git -C /home/sunkaijie/.cache/modelscope/hub/_github clone https://github.com/haotian-liu/LLaVA.git LLaVA.git`
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
Traceback (most recent call last):
  File "/home/sunkaijie/project/swift/swift/cli/infer.py", line 5, in <module>
    infer_main()
  File "/home/sunkaijie/project/swift/swift/utils/run_utils.py", line 31, in x_main
    result = llm_x(args, **kwargs)
  File "/home/sunkaijie/project/swift/swift/llm/infer.py", line 264, in llm_infer
    model, template = prepare_model_template(args)
  File "/home/sunkaijie/project/swift/swift/llm/infer.py", line 188, in prepare_model_template
    model, tokenizer = get_model_tokenizer(
  File "/home/sunkaijie/project/swift/swift/llm/utils/model.py", line 3625, in get_model_tokenizer
    model, tokenizer = get_function(model_dir, torch_dtype, model_kwargs,
  File "/home/sunkaijie/project/swift/swift/llm/utils/model.py", line 3376, in get_model_tokenizer_llava
    from llava.model import LlavaMistralForCausalLM, LlavaMistralConfig
ModuleNotFoundError: No module named 'llava'
运行代码出现这个错误，按照llava最佳实践.md操作所出现的

**Comment by hjh0119** [comment]
```
git clone https://github.com/haotian-liu/LLaVA.git
cd LLaVA
pip install --upgrade pip  # enable PEP 660 support
pip install -e .
```

**Comment by hjh0119** [comment]
>     python -m bitsandbytes

**Comment by SunLang115** [comment]
> > ```
> > python -m bitsandbytes
> > ```
我没有执行这步。
我删除了相关的虚拟环境，然后重新安装swift，现在出现这个问题：
(swift) [sunkaijie@localhost swift]$ CUDA_VISIBLE_DEVICES=0 swift infer --model_type minicpm-v-3b-chat
run sh: `python /home/sunkaijie/anaconda3/envs/swift/lib/python3.10/site-packages/swift/cli/infer.py --model_type minicpm-v-3b-chat`
2024-04-22 09:27:36,057 - modelscope - INFO - PyTorch version 2.2.2 Found.
2024-04-22 09:27:36,058 - modelscope - INFO - Loading ast index from /home/sunkaijie/.cache/modelscope/ast_indexer
2024-04-22 09:27:36,090 - modelscope - INFO - Loading done! Current index file version is 1.13.3, with md5 f5553e5334bc76dd72a1bc2a102a1cdb and a total number of 972 components indexed
Traceback (most recent call last):
  File "/home/sunkaijie/anaconda3/envs/swift/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 451, in _get_module
    return importlib.import_module('.' + module_name, self.__name__)
  File "/home/sunkaijie/anaconda3/envs/swift/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sunkaijie/anaconda3/envs/swift/lib/python3.10/site-packages/modelscope/msdatasets/__init__.py", line 2, in <module>
    from .ms_dataset import MsDataset
  File "/home/sunkaijie/anaconda3/envs/swift/lib/python3.10/site-packages/modelscope/msdatasets/ms_dataset.py", line 24, in <module>
    from modelscope.msdatasets.utils.hf_datasets_util import \
  File "/home/sunkaijie/anaconda3/envs/swift/lib/python3.10/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 42, in <module>
    from datasets.utils import _datasets_server, file_utils
ImportError: cannot import name '_datasets_server' from 'datasets.utils' (/home/sunkaijie/anaconda3/envs/swift/lib/python3.10/site-packages/datasets/utils/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sunkaijie/anaconda3/envs/swift/lib/python3.10/site-packages/swift/cli/infer.py", line 2, in <module>
    from swift.llm import infer_main
  File "/home/sunkaijie/anaconda3/envs/swift/lib/python3.10/site-packages/swift/llm/__init__.py", line 5, in <module>
    from .utils import *
  File "/home/sunkaijie/anaconda3/envs/swift/lib/python3.10/site-packages/swift/llm/utils/__init__.py", line 2, in <module>
    from .argument import (AppUIArguments, DeployArguments, DPOArguments,
  File "/home/sunkaijie/anaconda3/envs/swift/lib/python3.10/site-packages/swift/llm/utils/argument.py", line 26, in <module>
    from .dataset import (DATASET_MAPPING, get_custom_dataset, get_dataset,
  File "/home/sunkaijie/anaconda3/envs/swift/lib/python3.10/site-packages/swift/llm/utils/dataset.py", line 13, in <module>
    from modelscope import MsDataset
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/sunkaijie/anaconda3/envs/swift/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 434, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/sunkaijie/anaconda3/envs/swift/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 453, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import modelscope.msdatasets because of the following error (look up to see its traceback):
cannot import name '_datasets_server' from 'datasets.utils' (/home/sunkaijie/anaconda3/envs/swift/lib/python3.10/site-packages/datasets/utils/__init__.py)

**Comment by SunLang115** [comment]
> > ```
> > python -m bitsandbytes
> > ```

错误的办法

**Comment by hjh0119** [comment]
> cannot import name '_datasets_server' from 'datasets.utils' 

datasets 的版本手动限制在<=2.18.0, >=2.16.0

**Comment by SunLang115** [comment]
> > cannot import name '_datasets_server' from 'datasets.utils'
> 
> datasets 的版本手动限制在<=2.18.0, >=2.16.0

重新安装了虚拟环境，运行其他的多模态大模型了，Yi和llava还是不可以，依旧是出现ModuleNotFoundError: No module named 'llava'错误

**Comment by hjh0119** [comment]
> 重新安装了虚拟环境，运行其他的多模态大模型了，Yi和llava还是不可以，依旧是出现ModuleNotFoundError: No module named 'llava'错误

安装了llava吗
```
git clone https://github.com/haotian-liu/LLaVA.git
cd LLaVA
pip install --upgrade pip  # enable PEP 660 support
pip install -e .
```

**Comment by SunLang115** [comment]
> > 重新安装了虚拟环境，运行其他的多模态大模型了，Yi和llava还是不可以，依旧是出现ModuleNotFoundError: No module named 'llava'错误
> 
> 安装了llava吗
> 
> ```
> git clone https://github.com/haotian-liu/LLaVA.git
> cd LLaVA
> pip install --upgrade pip  # enable PEP 660 support
> pip install -e .
> ```

安装后出现这个问题，且无法解决，还会导致其他模型推理在swift环境下无法运行
CUDA Setup failed despite GPU being available. Please run the following command to get more information:

    python -m bitsandbytes

    Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
    to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
    and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
    
    之前运行llava项目就无法部署。

**Comment by hjh0119** [comment]
>  Run the command: git -C /home/sunkaijie/.cache/modelscope/hub/_github clone https://github.com/haotian-liu/LLaVA.git LLaVA.git
Unknown option: -C

更新下git版本再试下
