### ISSUE TITLE
Crash in training: KeyError: 'input_ids'

### ISSUE THREAD

**Issue by SinanAkkoyun** [modelscope/swift#777]
**Describe the bug**
```bash
Train:  12%|████████████                                                                                         | 944/7866 [51:45<6:21:13,  3.30s/it]Traceback (most recent call last):
  File "/home/ai/ml/vision/vlm/training/swift/swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/home/ai/ml/vision/vlm/training/swift/swift/swift/utils/run_utils.py", line 31, in x_main
    result = llm_x(args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/ml/vision/vlm/training/swift/swift/swift/llm/sft.py", line 261, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/home/ai/ml/vision/vlm/training/swift/swift/swift/trainers/trainers.py", line 54, in train
    res = super().train(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/.mconda3/envs/swift/lib/python3.11/site-packages/transformers/trainer.py", line 1780, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/.mconda3/envs/swift/lib/python3.11/site-packages/transformers/trainer.py", line 2085, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/ai/ml/vision/vlm/training/swift/swift/swift/trainers/trainers.py", line 282, in __next__
    return next(self._iterator)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/.mconda3/envs/swift/lib/python3.11/site-packages/accelerate/data_loader.py", line 462, in __iter__
    next_batch = next(dataloader_iter)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/.mconda3/envs/swift/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/ai/.mconda3/envs/swift/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/.mconda3/envs/swift/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/.mconda3/envs/swift/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/ai/ml/vision/vlm/training/swift/swift/swift/llm/utils/utils.py", line 206, in __getitem__
    res = self._try_fetch(idx)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/ml/vision/vlm/training/swift/swift/swift/llm/utils/utils.py", line 216, in _try_fetch
    res = self.template.encode(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/ml/vision/vlm/training/swift/swift/swift/llm/utils/template.py", line 1130, in encode
    input_ids, labels = inputs['input_ids'], inputs['labels']
                        ~~~~~~^^^^^^^^^^^^^
KeyError: 'input_ids'
```
For some reason, the encoding fails mid-training. The Deepseek encoder seems to not always work correctly, however I can not tell why that's the case... (I will in the mean time try to find the 'example' that is causing this)

It would be also practical to have a try catch, so that if one training example is faulty, the whole training is not aborted

Command:
```bash
CUDA_VISIBLE_DEVICES=3 swift sft \ 
          --model_type deepseek-vl-1_3b-chat \
          --custom_train_dataset_path dataset_swift.jsonl \
          --train_dataset_sample -1 \
          --sft_type full \
          --deepspeed default-zero2 \
          --num_train_epochs 1 \
          --evaluation_strategy no \
          --per_device_train_batch_size 10
```

**Your hardware and system info**
CUDA 12.2, torch 2.1.1

**Additional context**

**Comment by Jintao-Huang** [comment]
Try setting `--max_length -1`.

**Comment by SinanAkkoyun** [comment]
Thank you, it's training with `max_length -1`, I hope it doesn't crash
I also realized that the line causing the crash was (including user prompt) roughly 2840 tokens long

**Comment by Jintao-Huang** [comment]
In the latest version, --max_length will be set to -1 by default.

**Comment by SinanAkkoyun** [comment]
My complete training run just finished, it works, thank you!
