### ISSUE TITLE
量化baichuan2-7b 报错AttributeError: 'BaichuanAWQForCausalLM' object has no attribute 'lm_head'

### ISSUE THREAD

**Issue by greatheart1000** [modelscope/swift#785]
CUDA_VISIBLE_DEVICES=0 swift export \
     --model_type baichuan2-7b --quant_bits 4 \
     --quantization_bit 0 \
     --ckpt_dir  output/baichuan2-7b/v23-20240421-192531/checkpoint-870-merged \
     --custom_val_dataset_path test_set.jsonl  \
     --quant_device_map='cuda:0'  \
     --custom_train_dataset_path train_set.jsonl  --quant_method awq
     
     Loading the model using model_dir: /root/swift/examples/pytorch/llm/output/baichuan2-7b/v23-20240421-192531/checkpoint-870-merged
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████| 4/4 [00:04<00:00,  1.16s/it]
Traceback (most recent call last):
  File "/root/swift/swift/cli/export.py", line 5, in <module>
    export_main()
  File "/root/briaai/swift/swift/utils/run_utils.py", line 31, in x_main
    result = llm_x(args, **kwargs)
  File "/root/briaai/swift/swift/llm/export.py", line 131, in llm_export
    model, template = prepare_model_template(
  File "/root/briaai/swift/swift/llm/infer.py", line 165, in prepare_model_template
    model, tokenizer = get_model_tokenizer(
  File "/root/briaai/swift/swift/llm/utils/model.py", line 3889, in get_model_tokenizer
    model, tokenizer = get_function(model_dir, torch_dtype, model_kwargs,
  File "/root/briaai/swift/swift/llm/utils/model.py", line 1091, in get_model_tokenizer_baichuan2
    model.lm_head)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'BaichuanAWQForCausalLM' object has no attribute 'lm_head'

**Comment by Jintao-Huang** [comment]
fixed, main分支
