### ISSUE TITLE
源码安装swift报错

### ISSUE THREAD

**Issue by zhangfan-algo** [modelscope/swift#845]
![image](https://github.com/modelscope/swift/assets/47747764/ef8e19d9-23c7-48cb-9ffb-b0b1dc085123)
硬件配置：4台8*a800

**Comment by zhangfan-algo** [comment]
怀疑是多线程冲突引起的

**Comment by Jintao-Huang** [comment]
卸载干净 再装一下呗

**Comment by zhangfan-algo** [comment]
Traceback (most recent call last):
  File "/mnt/pfs/zhangfan/homework_correction/swift_0429/examples/pytorch/llm/llm_sft.py", line 7, in <module>
    output = sft_main()
  File "/mnt/pfs/zhangfan/homework_correction/swift_0429/swift/utils/run_utils.py", line 31, in x_main
    result = llm_x(args, **kwargs)
  File "/mnt/pfs/zhangfan/homework_correction/swift_0429/swift/llm/sft.py", line 265, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/mnt/pfs/zhangfan/homework_correction/swift_0429/swift/trainers/trainers.py", line 54, in train
    res = super().train(*args, **kwargs)
  File "/apps1/zhangfan/anaconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 1624, in train
    return inner_training_loop(
  File "/apps1/zhangfan/anaconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 1928, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/apps1/zhangfan/anaconda3/envs/swift/lib/python3.10/site-packages/accelerate/data_loader.py", line 452, in __iter__
    current_batch = next(dataloader_iter)
  File "/apps1/zhangfan/anaconda3/envs/swift/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/apps1/zhangfan/anaconda3/envs/swift/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/apps1/zhangfan/anaconda3/envs/swift/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/mnt/pfs/zhangfan/homework_correction/swift_0429/swift/llm/utils/template.py", line 1050, in data_collator
    res = super().data_collator(batch, padding_to)
  File "/mnt/pfs/zhangfan/homework_correction/swift_0429/swift/llm/utils/template.py", line 436, in data_collator
    input_ids = [torch.tensor(b['input_ids']) for b in batch]
  File "/mnt/pfs/zhangfan/homework_correction/swift_0429/swift/llm/utils/template.py", line 436, in <listcomp>
    input_ids = [torch.tensor(b['input_ids']) for b in batch]
KeyError: 'input_ids'
目前先在单台机器上试跑 有这个报错

**Comment by Jintao-Huang** [comment]
什么模型呀

**Comment by zhangfan-algo** [comment]
internvl-chat-v1_5

**Comment by hjh0119** [comment]
方便提供下sft命令和数据样例？

**Comment by zhangfan-algo** [comment]
> 方便提供下sft命令和数据样例？

num_nodes=8
num_gpu_per_node=8
node_rank=0
master_addr=0.0.0.0
master_port=6009

torchrun  --nproc_per_node ${num_gpu_per_node}  --master_port ${master_port} --master_addr ${master_addr} --node_rank ${node_rank}  examples/pytorch/llm/llm_sft.py \
    --model_cache_dir /mnt/pfs/zhangfan/models/OpenGVLab/InternVL-Chat-V1-5 \
    --model_type internvl-chat-v1_5  \
    --sft_type lora \
    --lora_target_modules DEFAULT \
    --tuner_backend swift \
    --template_type AUTO \
    --output_dir output/google_mathwriting_sft_0429 \
    --ddp_backend nccl \
    --custom_train_dataset_path data/google_mathwriting_symbols_internvl_chat_swift_baige.jsonl data/google_mathwriting_synthetic_internvl_chat_swift_baige.jsonl data/google_mathwriting_train_internvl_chat_swift_baige.jsonl \
    --custom_val_dataset_path data/google_mathwriting_valid_internvl_chat_swift_baige.jsonl \
    --system "你是一名数学手写体OCR识别专家。" \
    --self_cognition_sample -1 \
    --preprocess_num_proc 60 \
    --dataloader_num_workers 60 \
    --train_dataset_sample -1 \
    --val_dataset_sample -1 \
    --save_strategy steps \
    --lr_scheduler_type cosine \
    --save_total_limit 10 \
    --save_steps 1000 \
    --eval_steps 1000 \
    --max_steps 5000 \
    --logging_steps 10 \
    --max_length 1024 \
    --check_dataset_strategy warning \
    --gradient_checkpointing false \
    --batch_size 8 \
    --eval_batch_size 8 \
    --gradient_accumulation_steps 1 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --use_flash_attn false \
    --push_to_hub false \
    --deepspeed_config_path default-zero2 \
    --save_only_model false \
    --save_on_each_node false \
    --lazy_tokenize true \
    --dtype AUTO

**Comment by zhangfan-algo** [comment]
> 方便提供下sft命令和数据样例？

{'query': '这是学生书写的数字和数学公式相关内容。请你准确说出图片中手写体内容是什么.数学公式用latex表达。你的输出格式必须是：图片中手写体内容是:XXX.let us think step by step',
 'response': '图片中手写体内容是:(数学公式用latex公式表达)\n\nn',
 'images': ['/mnt/pfs/zhangfan/homework_correction/mathwriting_data/mathwriting_symbols/1185.png']}

**Comment by hjh0119** [comment]
--max_length 1024 太小了，图像部分vit的embeds长度一般都超过1024了。

**Comment by zhangfan-algo** [comment]
好的 我试试

**Comment by zhangfan-algo** [comment]
大佬 可以了 还想问下 我们目前支持epoch的方式保存模型不

**Comment by hjh0119** [comment]
> 大佬 可以了 还想问下 我们目前支持epoch的方式保存模型不

@Jintao-Huang

**Comment by zhangfan-algo** [comment]
> 建议设到2048以上

大佬 单机8卡跑没啥问题，改成多节点跑就不行了
![Uploading image.png…]()

**Comment by tastelikefeet** [comment]
目前不支持，仅支持step方式，可以考虑将--save_steps设置为和一个epoch相匹配

**Comment by zhangfan-algo** [comment]
> 卸载干净 再装一下呗
大佬 虚拟环境之前没有装swift  重新跑了一下  还是报错了
