### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by mayiming0708** [modelscope/swift#965]
我在部署internvl-chat-v1_5时遇到了与[#734 ](https://github.com/modelscope/swift/issues/734)相同的问题，重新pull后无用，是否需要修改相关代码
```
Traceback (most recent call last):
  File "/data/conda/env/swift/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/conda/env/swift/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/data/conda/env/swift/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/data/conda/env/swift/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/conda/env/swift/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/data/conda/env/swift/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/data/conda/env/swift/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/data/conda/env/swift/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/data/conda/env/swift/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/data/conda/env/swift/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/conda/env/swift/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/data/conda/env/swift/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/data/conda/env/swift/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/data/conda/env/swift/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/data/conda/env/swift/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/data/conda/env/swift/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/data/conda/env/swift/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/data/conda/env/swift/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/mym/swift/swift/llm/deploy.py", line 415, in create_chat_completion
    return await inference_pt_async(request, raw_request)
  File "/data/mym/swift/swift/llm/deploy.py", line 287, in inference_pt_async
    error_msg = await check_length(request, input_ids)
  File "/data/mym/swift/swift/llm/deploy.py", line 57, in check_length
    max_tokens = max_model_len - num_tokens
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by hjh0119** [comment]
多模态模型的部署还在开发中 推理正常吗

**Comment by mayiming0708** [comment]
> 多模态模型的部署还在开发中 推理正常吗

推理是正常的
