### ISSUE TITLE
qwen1half-14b-chat-int4使用lora微调后合并模型报错

### ISSUE THREAD

**Issue by AnsongLi** [modelscope/swift#966]
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.11/site-packages/swift/cli/export.py", line 5, in <module>
    export_main()
  File "/root/miniconda3/lib/python3.11/site-packages/swift/utils/run_utils.py", line 31, in x_main
    result = llm_x(args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/swift/llm/export.py", line 110, in llm_export
    merge_lora(args, device_map=args.merge_device_map)
  File "/root/miniconda3/lib/python3.11/site-packages/swift/llm/infer.py", line 87, in merge_lora
    assert s not in args.model_type, f'{s} model is not supported'
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: int4 model is not supported

qwen1half-14b-chat-int4使用lora微调后合并模型报错，请问为什么不知道int4模型的合并呢？
是因为模型参数单位int4和lora tf16不匹配吗，有什么方法能解决呢？

**Comment by tastelikefeet** [comment]
int4模型不能合并lora的
