### ISSUE TITLE
支持swift接入数据集的下载和离线训练。

### ISSUE THREAD

**Issue by stitchshaw** [modelscope/swift#982]
**Describe the feature**
问题出在离线环境下，指定数据集时需要联网下载。即便之前在有网条件下已经将数据集下载到~/.cache/modelscope/hub/datasets中。

**Paste any useful information**
代码版本：v2.0.4
数据集：https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E6%94%AF%E6%8C%81%E7%9A%84%E6%A8%A1%E5%9E%8B%E5%92%8C%E6%95%B0%E6%8D%AE%E9%9B%86.md#%E6%95%B0%E6%8D%AE%E9%9B%86
CUDA_VISIBLE_DEVICES=6,7
swift sft \
    --model_id_or_path /share/home/Jinzw003/checkpoints/Qwen/Qwen1.5-7B-Chat \
    --model_type qwen1half-7b-chat \
    --dataset ms-agent agent-instruct-all-en ms-agent-multirole  \
    --train_dataset_mix_ratio 2 \
    --self_cognition_sample 3000 \
    --dataset_test_ratio 0.05 \
    --max_length 4096 \
    --learning_rate 5e-5 \
    --check_model_is_latest False \
    --truncation_strategy delete \
    --model_name k-agent \
    --model_author kingsware \
    --use_loss_scale True \
    --model_revision master \
    --sft_type lora \
    --tuner_backend peft \
    --dtype AUTO \
    --output_dir output \
    --num_train_epochs 2 \
    --check_dataset_strategy warning \
    --lora_target_modules ALL \
    --gradient_checkpointing true \
    --batch_size 2 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10

报错信息：
Traceback (most recent call last):
  File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/swift/utils/run_utils.py", line 27, in x_main
    result = llm_x(args, **kwargs)
  File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/swift/llm/sft.py", line 131, in llm_sft
    train_dataset, val_dataset = get_dataset(
  File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/swift/llm/utils/dataset.py", line 1525, in get_dataset
    dataset = get_function(
  File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/swift/llm/utils/dataset.py", line 333, in get_dataset_from_repo
    dataset = load_ms_dataset(dataset_id, subset_split_list)
  File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/swift/llm/utils/dataset.py", line 237, in load_ms_dataset
    dataset = MsDataset.load(dataset_id, subset_name=subset_name, split=split, download_mode=download_mode)
  File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/swift/llm/utils/utils.py", line 96, in _msdataset_ddp_load
    dataset = _old_msdataset_load(*args, **kwargs)
  File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/modelscope/msdatasets/ms_dataset.py", line 288, in load
    dataset_id_on_hub, dataset_type = _api.get_dataset_id_and_type(
  File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/modelscope/hub/api.py", line 704, in get_dataset_id_and_type
    r = self.session.get(datahub_url, cookies=cookies)
  File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/datasets/iic/ms_agent (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4bac214a60>: Failed to resolve 'www.modelscope.cn' ([Errno -3] Temporary failure in name resolution)"))

**Comment by stitchshaw** [comment]
v2.0.4版本下：
可以先这样
`    train_dataset, val_dataset = get_dataset(
        "ms-agent",
        0,
        random_state,
        check_dataset_strategy="warning")`
将数据保存为jsonl。然后指定--custom_train_dataset_path 即可

**Comment by nickyi1990** [comment]
> Referenc

我今天测试这个问题，现在这个问题还没被解决，有计划用缓存而不是这种临时的方法么
